## GDP dataset ##

### Packages and dataset ###

In [18]:
#IMPORT NEEDED PACKAGES

import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
import pandas as pd
import numpy as np
pd.options.display.max_columns = None

In [19]:
# READ RAW CSV
df_raw = pd.read_csv('../../Macro-Statistics_Key_Indicators/Macro-Statistics_Key_Indicators_E_All_Data.csv', encoding = 'latin')

### Exploring the data ###

In [20]:
df_raw.shape

(15799, 161)

In [21]:
df_raw.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1970,Y1970F,Y1970N,Y1971,Y1971F,Y1971N,Y1972,Y1972F,Y1972N,Y1973,Y1973F,Y1973N,Y1974,Y1974F,Y1974N,Y1975,Y1975F,Y1975N,Y1976,Y1976F,Y1976N,Y1977,Y1977F,Y1977N,Y1978,Y1978F,Y1978N,Y1979,Y1979F,Y1979N,Y1980,Y1980F,Y1980N,Y1981,Y1981F,Y1981N,Y1982,Y1982F,Y1982N,Y1983,Y1983F,Y1983N,Y1984,Y1984F,Y1984N,Y1985,Y1985F,Y1985N,Y1986,Y1986F,Y1986N,Y1987,Y1987F,Y1987N,Y1988,Y1988F,Y1988N,Y1989,Y1989F,Y1989N,Y1990,Y1990F,Y1990N,Y1991,Y1991F,Y1991N,Y1992,Y1992F,Y1992N,Y1993,Y1993F,Y1993N,Y1994,Y1994F,Y1994N,Y1995,Y1995F,Y1995N,Y1996,Y1996F,Y1996N,Y1997,Y1997F,Y1997N,Y1998,Y1998F,Y1998N,Y1999,Y1999F,Y1999N,Y2000,Y2000F,Y2000N,Y2001,Y2001F,Y2001N,Y2002,Y2002F,Y2002N,Y2003,Y2003F,Y2003N,Y2004,Y2004F,Y2004N,Y2005,Y2005F,Y2005N,Y2006,Y2006F,Y2006N,Y2007,Y2007F,Y2007N,Y2008,Y2008F,Y2008N,Y2009,Y2009F,Y2009N,Y2010,Y2010F,Y2010N,Y2011,Y2011F,Y2011N,Y2012,Y2012F,Y2012N,Y2013,Y2013F,Y2013N,Y2014,Y2014F,Y2014N,Y2015,Y2015F,Y2015N,Y2016,Y2016F,Y2016N,Y2017,Y2017F,Y2017N,Y2018,Y2018F,Y2018N,Y2019,Y2019F,Y2019N,Y2020,Y2020F,Y2020N
0,2,'004,Afghanistan,22008,Gross Domestic Product,6109,Value Local Currency,millions,77.911878,X,NaN,81.574837,X,NaN,74.152916,X,NaN,76.619555,X,NaN,92.774575,X,NaN,104.385259,X,NaN,113.107176,X,NaN,128.917758,X,NaN,145.028303,X,NaN,158.776212,X,NaN,160.930107,X,NaN,169.591475,X,NaN,173.589299,X,NaN,172.453817,X,NaN,170.475688,X,NaN,168.520249,X,NaN,168.035667,X,NaN,150.976242,X,NaN,137.322243,X,NaN,161.491528,X,NaN,180.109889,X,NaN,172.172997,X,NaN,174.301038,X,NaN,143.927675,X,NaN,729.118301,X,NaN,2297.365030,X,NaN,6674.524156,X,NaN,8773.855716,X,NaN,8805.572314,X,NaN,100567.527295,X,NaN,158270.632870,X,NaN,170927.404578,X,NaN,195740.846106,X,NaN,230601.118468,X,NaN,257813.610332,X,NaN,307884.813631,X,NaN,354705.069349,X,NaN,470250.593341,X,NaN,514400.361283,X,NaN,583525.091849,X,NaN,682799.599547,X,NaN,811093.070883,X,NaN,9.744573e+05,X,NaN,1.086606e+06,X,NaN,1.119229e+06,X,NaN,1.144181e+06,X,NaN,1.222917e+06,X,NaN,1.285460e+06,X,NaN,1.327690e+06,X,NaN,1.469596e+06,X,NaN,1.520390e+06,X,NaN
1,2,'004,Afghanistan,22008,Gross Domestic Product,6110,Value US$,millions,1731.435587,X,NaN,1812.837521,X,NaN,1647.900178,X,NaN,1702.716294,X,NaN,2061.729287,X,NaN,2319.753506,X,NaN,2513.580659,X,NaN,2864.939207,X,NaN,3222.963833,X,NaN,3630.767856,X,NaN,3646.796868,X,NaN,3427.482014,X,NaN,3430.645143,X,NaN,3408.204613,X,NaN,3369.110951,X,NaN,3330.465681,X,NaN,3320.888887,X,NaN,2983.743471,X,NaN,2713.899488,X,NaN,3191.557068,X,NaN,3559.511736,X,NaN,3402.654940,X,NaN,3444.711414,X,NaN,2844.442641,X,NaN,1715.169169,X,NaN,2756.838036,X,NaN,2669.785634,X,NaN,2924.589326,X,NaN,2935.139404,X,NaN,2157.197316,X,NaN,3342.034168,X,NaN,3598.470576,X,NaN,4141.523943,X,NaN,4729.042179,X,NaN,5388.482107,X,NaN,6220.574147,X,NaN,7104.711445,X,NaN,9412.161765,X,NaN,10236.901594,X,NaN,11595.133469,X,NaN,14698.889678,X,NaN,17350.694945,X,NaN,1.913650e+04,X,NaN,1.962180e+04,X,NaN,1.955070e+04,X,NaN,1.871305e+04,X,NaN,1.801956e+04,X,NaN,1.889635e+04,X,NaN,1.841885e+04,X,NaN,1.890449e+04,X,NaN,1.979326e+04,X,NaN
2,2,'004,Afghanistan,22008,Gross Domestic Product,6119,Value US$ per capita,US$,154.957138,X,NaN,157.975357,X,NaN,139.756605,X,NaN,140.616194,X,NaN,166.095029,X,NaN,182.813796,X,NaN,194.202472,X,NaN,217.513678,X,NaN,241.579792,X,NaN,270.729453,X,NaN,273.035141,X,NaN,260.216148,X,NaN,266.302169,X,NaN,271.835860,X,NaN,276.059517,X,NaN,278.975344,X,NaN,282.961677,X,NaN,257.118767,X,NaN,233.594278,X,NaN,268.901352,X,NaN,286.772753,X,NaN,255.857628,X,NaN,237.803353,X,NaN,179.839036,X,NaN,100.444869,X,NaN,152.221868,X,NaN,141.607370,X,NaN,151.085927,X,NaN,148.706776,X,NaN,106.946309,X,NaN,160.829727,X,NaN,166.541981,X,NaN,183.247028,X,NaN,199.698828,X,NaN,217.921744,X,NaN,242.477079,X,NaN,268.781382,X,NaN,347.305373,X,NaN,369.266275,X,NaN,408.353930,X,NaN,503.636606,X,NaN,576.101770,X,NaN,6.141096e+02,X,NaN,6.080586e+02,X,NaN,5.858627e+02,X,NaN,5.437689e+02,X,NaN,5.092712e+02,X,NaN,5.206164e+02,X,NaN,4.955043e+02,X,NaN,4.969406e+02,X,NaN,5.084537e+02,X,NaN
3,2,'004,Afghanistan,22008,Gross Domestic Product,6183,"Value Local Currency, 2015 prices",millions,640024.694809,X,NaN,638260.085798,X,NaN,556498.281260,X,NaN,545260.592016,X,NaN,571963.541311,X,NaN,606538.115012,X,NaN,640652.358105,X,NaN,622700.035211,X,NaN,650881.544583,X,NaN,647761.511702,X,NaN,625359.636217,X,NaN,630423.153215,X,NaN,643414.185241,X,NaN,670981.813064,X,NaN,687706.446508,X,NaN,691900.378533,X,NaN,708420.513683,X,NaN,656098.152210,X,NaN,598661.464479,X,NaN,554676.102558,X,NaN,532223.150831,X,NaN,483512.600665,X,NaN,476587.229752,X,NaN,385407.968239,X,NaN,296737.925985,X,NaN,387337.309453,X,NaN,401148.285358,X,NaN,380405.169744,X,NaN,362609.298241,X,NaN,345273.395382,X,NaN,326789.905499,X,NaN,308373.050408,X,NaN,458140.931411,X,NaN,530558.854216,X,NaN,545734.797948,X,NaN,586710.864491,X,NaN,636952.631554,X,NaN,781177.101080,X,NaN,772544.956581,X,NaN,856508.039841,X,NaN,901472.494035,X,NaN,962434.513050,X,NaN,1.055821e+06,X,NaN,1.126041e+06,X,NaN,1.160649e+06,X,NaN,1.144181e+06,X,NaN,1.161900e+06,X,NaN,1.192655e+06,X,NaN,1.206839e+06,X,NaN,1.254046e+06,X,NaN,1.229783e+06,X,NaN
4,2,'004,Afghanistan,22008,Gross Domestic Product,6185,"Value US$ per capita, 2015 prices",US$,937.000000,X,NaN,910.000000,X,NaN,772.000000,X,NaN,736.000000,X,NaN,754.000000,X,NaN,782.000000,X,NaN,810.000000,X,NaN,773.000000,X,NaN,798.000000,X,NaN,790.000000,X,NaN,766.000000,X,NaN,783.000000,X,NaN,817.000000,X,NaN,875.000000,X,NaN,922.000000,X,NaN,948.000000,X,NaN,987.000000,X,NaN,925.000000,X,NaN,843.000000,X,NaN,764.000000,X,NaN,701.000000,X,NaN,595.000000,X,NaN,538.000000,X,NaN,399.000000,X,NaN,284.000000,X,NaN,350.000000,X,NaN,348.000000,X,NaN,321.000000,X,NaN,300.000000,X,NaN,280.000000,X,NaN,257.000000,X,NaN,233.000000,X,NaN,332.000000,X,NaN,366.000000,X,NaN,361.000000,X,NaN,374.000000,X,NaN,394.000000,X,NaN,471.000000,X,NaN,456.000000,X,NaN,493.000000,X,NaN,505.000000,X,NaN,523.000000,X,NaN,5.540000e+02,X,NaN,5.710000e+02,X,NaN,5.690000e+02,X,NaN,5.440000e+02,X,NaN,5.370000e+02,X,NaN,5.370000e+02,X,NaN,5.310000e+02,X,NaN,5.390000e+02,X,NaN,5.170000e+02,X,NaN

In [22]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15799 entries, 0 to 15798
Columns: 161 entries, Area Code to Y2020N
dtypes: float64(102), int64(3), object(56)
memory usage: 19.4+ MB

In [23]:
#Goal: Simplify the dataframe by deleting Year+F and Year+N
column_headers = list(df_raw.columns.values)
column_headers

['Area Code',
 'Area Code (M49)',
 'Area',
 'Item Code',
 'Item',
 'Element Code',
 'Element',
 'Unit',
 'Y1970',
 'Y1970F',
 'Y1970N',
 'Y1971',
 'Y1971F',
 'Y1971N',
 'Y1972',
 'Y1972F',
 'Y1972N',
 'Y1973',
 'Y1973F',
 'Y1973N',
 'Y1974',
 'Y1974F',
 'Y1974N',
 'Y1975',
 'Y1975F',
 'Y1975N',
 'Y1976',
 'Y1976F',
 'Y1976N',
 'Y1977',
 'Y1977F',
 'Y1977N',
 'Y1978',
 'Y1978F',
 'Y1978N',
 'Y1979',
 'Y1979F',
 'Y1979N',
 'Y1980',
 'Y1980F',
 'Y1980N',
 'Y1981',
 'Y1981F',
 'Y1981N',
 'Y1982',
 'Y1982F',
 'Y1982N',
 'Y1983',
 'Y1983F',
 'Y1983N',
 'Y1984',
 'Y1984F',
 'Y1984N',
 'Y1985',
 'Y1985F',
 'Y1985N',
 'Y1986',
 'Y1986F',
 'Y1986N',
 'Y1987',
 'Y1987F',
 'Y1987N',
 'Y1988',
 'Y1988F',
 'Y1988N',
 'Y1989',
 'Y1989F',
 'Y1989N',
 'Y1990',
 'Y1990F',
 'Y1990N',
 'Y1991',
 'Y1991F',
 'Y1991N',
 'Y1992',
 'Y1992F',
 'Y1992N',
 'Y1993',
 'Y1993F',
 'Y1993N',
 'Y1994',
 'Y1994F',
 'Y1994N',
 'Y1995',
 'Y1995F',
 'Y1995N',
 'Y1996',
 'Y1996F',
 'Y1996N',
 'Y1997',
 'Y1997F',
 'Y1997N',
 'Y1998',
 'Y1998F',
 'Y1998N',
 'Y1999',
 'Y1999F',
 'Y1999N',
 'Y2000',
 'Y2000F',
 'Y2000N',
 'Y2001',
 'Y2001F',
 'Y2001N',
 'Y2002',
 'Y2002F',
 'Y2002N',
 'Y2003',
 'Y2003F',
 'Y2003N',
 'Y2004',
 'Y2004F',
 'Y2004N',
 'Y2005',
 'Y2005F',
 'Y2005N',
 'Y2006',
 'Y2006F',
 'Y2006N',
 'Y2007',
 'Y2007F',
 'Y2007N',
 'Y2008',
 'Y2008F',
 'Y2008N',
 'Y2009',
 'Y2009F',
 'Y2009N',
 'Y2010',
 'Y2010F',
 'Y2010N',
 'Y2011',
 'Y2011F',
 'Y2011N',
 'Y2012',
 'Y2012F',
 'Y2012N',
 'Y2013',
 'Y2013F',
 'Y2013N',
 'Y2014',
 'Y2014F',
 'Y2014N',
 'Y2015',
 'Y2015F',
 'Y2015N',
 'Y2016',
 'Y2016F',
 'Y2016N',
 'Y2017',
 'Y2017F',
 'Y2017N',
 'Y2018',
 'Y2018F',
 'Y2018N',
 'Y2019',
 'Y2019F',
 'Y2019N',
 'Y2020',
 'Y2020F',
 'Y2020N']

In [24]:
for col in df_raw.columns:
    if 'F' in col:
        df_raw.drop(col, axis=1, inplace=True)
    if 'N' in col:
        df_raw.drop(col, axis=1, inplace=True)

In [25]:
df_raw

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020
0,2,'004,Afghanistan,22008,Gross Domestic Product,6109,Value Local Currency,millions,77.911878,81.574837,74.152916,76.619555,92.774575,104.385259,113.107176,128.917758,145.028303,158.776212,160.930107,169.591475,173.589299,172.453817,170.475688,168.520249,168.035667,150.976242,137.322243,161.491528,180.109889,172.172997,174.301038,143.927675,729.118301,2297.365030,6674.524156,8773.855716,8805.572314,100567.527295,158270.632870,170927.404578,195740.846106,230601.118468,257813.610332,307884.813631,354705.069349,470250.593341,514400.361283,583525.091849,682799.599547,811093.070883,9.744573e+05,1.086606e+06,1.119229e+06,1.144181e+06,1.222917e+06,1.285460e+06,1.327690e+06,1.469596e+06,1.520390e+06
1,2,'004,Afghanistan,22008,Gross Domestic Product,6110,Value US$,millions,1731.435587,1812.837521,1647.900178,1702.716294,2061.729287,2319.753506,2513.580659,2864.939207,3222.963833,3630.767856,3646.796868,3427.482014,3430.645143,3408.204613,3369.110951,3330.465681,3320.888887,2983.743471,2713.899488,3191.557068,3559.511736,3402.654940,3444.711414,2844.442641,1715.169169,2756.838036,2669.785634,2924.589326,2935.139404,2157.197316,3342.034168,3598.470576,4141.523943,4729.042179,5388.482107,6220.574147,7104.711445,9412.161765,10236.901594,11595.133469,14698.889678,17350.694945,1.913650e+04,1.962180e+04,1.955070e+04,1.871305e+04,1.801956e+04,1.889635e+04,1.841885e+04,1.890449e+04,1.979326e+04
2,2,'004,Afghanistan,22008,Gross Domestic Product,6119,Value US$ per capita,US$,154.957138,157.975357,139.756605,140.616194,166.095029,182.813796,194.202472,217.513678,241.579792,270.729453,273.035141,260.216148,266.302169,271.835860,276.059517,278.975344,282.961677,257.118767,233.594278,268.901352,286.772753,255.857628,237.803353,179.839036,100.444869,152.221868,141.607370,151.085927,148.706776,106.946309,160.829727,166.541981,183.247028,199.698828,217.921744,242.477079,268.781382,347.305373,369.266275,408.353930,503.636606,576.101770,6.141096e+02,6.080586e+02,5.858627e+02,5.437689e+02,5.092712e+02,5.206164e+02,4.955043e+02,4.969406e+02,5.084537e+02
3,2,'004,Afghanistan,22008,Gross Domestic Product,6183,"Value Local Currency, 2015 prices",millions,640024.694809,638260.085798,556498.281260,545260.592016,571963.541311,606538.115012,640652.358105,622700.035211,650881.544583,647761.511702,625359.636217,630423.153215,643414.185241,670981.813064,687706.446508,691900.378533,708420.513683,656098.152210,598661.464479,554676.102558,532223.150831,483512.600665,476587.229752,385407.968239,296737.925985,387337.309453,401148.285358,380405.169744,362609.298241,345273.395382,326789.905499,308373.050408,458140.931411,530558.854216,545734.797948,586710.864491,636952.631554,781177.101080,772544.956581,856508.039841,901472.494035,962434.513050,1.055821e+06,1.126041e+06,1.160649e+06,1.144181e+06,1.161900e+06,1.192655e+06,1.206839e+06,1.254046e+06,1.229783e+06
4,2,'004,Afghanistan,22008,Gross Domestic Product,6185,"Value US$ per capita, 2015 prices",US$,937.000000,910.000000,772.000000,736.000000,754.000000,782.000000,810.000000,773.000000,798.000000,790.000000,766.000000,783.000000,817.000000,875.000000,922.000000,948.000000,987.000000,925.000000,843.000000,764.000000,701.000000,595.000000,538.000000,399.000000,284.000000,350.000000,348.000000,321.000000,300.000000,280.000000,257.000000,233.000000,332.000000,366.000000,361.000000,374.000000,394.000000,471.000000,456.000000,493.000000,505.000000,523.000000,5.540000e+02,5.710000e+02,5.690000e+02,5.440000e+02,5.370000e+02,5.370000e+02,5.310000e+02,5.390000e+02,5.170000e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15794,5817,'902,Net Food Importing Developing Countries,22011,Gross National Income,6103,Share of GDP US$,%,97.416450,97.135921,97.242871,97.341419,98.086288,98.670127,98.476801,98.616841,99.070057,98.919845,99.178230,99.125775,97.714213,97.742129,98.140452,96.883228,97.714363,98.145659,97.541659,97.442350,97.181878,97.305385,95.481618,96.310270,96.263928,97.663603,97.325683,97.874882,98.052489,97.706954,97.537878,97.593593,97.435307,97.738510,97.275909,97.340734,97.678919,98.043392,97.816958,98.356399,98.306356,98.451889,9.856416e+01,9.843464e+01,9.887750e+01,9.923226e+01,9.905498e+01,9.828360e+01,9.781773e+01,9.767972e+01,9.862552e+01
15795,5817,'902,Net Food Importing Developing Countries,22011,Gross National Income,6129,Annual growth US$,%,NaN,7.465709,6.126472,16.943898,26.198685,12.464953,8.058114,12.858459,14.323827,11.196998,17.109434,1.859547,-0.441168,-0.679872,-2.608620,-0.503123,8.319574,4.542378,7.722818,1.366287,5.892764,4.382471,3.858654,-0.085825,4.322462,15.915419,2.901941,6.876795,2.536937,1.691294,4.634836,1.249051,0.173212,6.246079,14.531149,17.015411,17.556465,18.545327,19.015776,2.693287,13.109307,8.093558,8.896547e+00,3.952822e+00,7.392885e+00,-1.168416e+00,-1.675270e+00,2.413034e+00,7.868940e-01,1.621622e+00,4.297660e-01
15796,5817,'902,Net Food Importing Developing Countries,22011,Gross National Income,61290,Annual growth US$ per capita,%,NaN,4.806655,3.408209,14.312631,23.178024,9.689742,5.366832,10.019574,11.456917,8.378599,14.153646,-0.789407,-3.011353,-3.262639,-5.158464,-3.048737,5.597717,1.748552,4.956140,-2.082494,6.990427,1.513612,1.851420,-6.624027,1.719424,13.074847,0.428428,4.353499,0.152829,-0.646282,2.250334,-1.041751,-2.075956,3.881991,12.010819,14.470924,15.032561,16.026650,16.393088,0.814755,10.240427,5.257139,7.274986e+00,1.701644e+00,5.080866e+00,-3.274219e+00,-3.745394e+00,2.799730e-01,-1.293156e+00,-4.618900e-01,-1.618741e+00
15797,5817,'902,Net Food Importing Developing Countries,22011,Gross National Income,6143,Share of Value Added (Total Manufacturing) US$,%,686.881551,676.479644,671.724619,661.442520,632.118942,649.562507,640.269886,655.832235,663.095326,642.740757,655.370005,670.410158,644.101913,633.060985,640.673022,633.102570,617.967989,660.540744,627.406159,656.043681,651.453759,671.216012,662.743428,669.618761,665.253481,660.441251,644.287281,645.936784,666.157888,678.879418,674.554744,682.216642,693.853959,700.480873,685.540319,706.525416,726.247568,733.802550,731.460808,721.209307,736.956601,745.900645,7.450676e+02,7.563768e+02,7.647168e+02,7.575890e+02,7.503457e+02,7.630487e+02,7.494638e+02,7.118064e+02,7.344206e+02
15798,5817,'902,Net Food Importing Developing Countries,22011,Gross National Income,6163,"Ratio of Value Added (Agriculture, Forestry an...",NaN,3.915855,4.053454,4.128555,4.238039,4.411620,4.351000,4.390226,4.482966,4.502286,4.686605,4.979382,5.097277,5.044219,4.967044,4.950164,4.697094,4.594868,4.758592,4.799879,4.682256,4.657795,4.565794,4.696011,4.775383,5.146858,5.335704,5.412539,5.537437,5.633895,5.862806,6.279319,6.435925,6.380209,6.261329,6.565978,6.814907,7.090996,7.141387,7.145942,6.774032,6.975336,6.787165,7.107360e+00,7.139002e+00,7.091600e+00,6.960310e+00,6.759811e+00,6.591877e+00,6.996136e+00,6.992809e+00,6.487359e+00

Annual growth rate of real Gross Domestic Product (GDP) per capita is calculated as the percentage change in the real GDP per capita between two consecutive years. Real GDP per capita is calculated by dividing GDP at constant prices by the population of a country or area. The data for real GDP are measured in constant US dollars to facilitate the calculation of country growth rates and aggregation of the country data.

In [26]:
#Only interested in the GDP with elements: Value US$, 2015 prices(expressed in millions), Value US$ per capita(US$), Annual growth US$ (%), Annual growth US$ per capita(%)

df = df_raw[df_raw['Item'] == 'Gross Domestic Product']
df.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020
0,2,'004,Afghanistan,22008,Gross Domestic Product,6109,Value Local Currency,millions,77.911878,81.574837,74.152916,76.619555,92.774575,104.385259,113.107176,128.917758,145.028303,158.776212,160.930107,169.591475,173.589299,172.453817,170.475688,168.520249,168.035667,150.976242,137.322243,161.491528,180.109889,172.172997,174.301038,143.927675,729.118301,2297.365030,6674.524156,8773.855716,8805.572314,100567.527295,158270.632870,170927.404578,195740.846106,230601.118468,257813.610332,307884.813631,354705.069349,470250.593341,514400.361283,583525.091849,682799.599547,811093.070883,9.744573e+05,1.086606e+06,1.119229e+06,1.144181e+06,1.222917e+06,1.285460e+06,1.327690e+06,1.469596e+06,1.520390e+06
1,2,'004,Afghanistan,22008,Gross Domestic Product,6110,Value US$,millions,1731.435587,1812.837521,1647.900178,1702.716294,2061.729287,2319.753506,2513.580659,2864.939207,3222.963833,3630.767856,3646.796868,3427.482014,3430.645143,3408.204613,3369.110951,3330.465681,3320.888887,2983.743471,2713.899488,3191.557068,3559.511736,3402.654940,3444.711414,2844.442641,1715.169169,2756.838036,2669.785634,2924.589326,2935.139404,2157.197316,3342.034168,3598.470576,4141.523943,4729.042179,5388.482107,6220.574147,7104.711445,9412.161765,10236.901594,11595.133469,14698.889678,17350.694945,1.913650e+04,1.962180e+04,1.955070e+04,1.871305e+04,1.801956e+04,1.889635e+04,1.841885e+04,1.890449e+04,1.979326e+04
2,2,'004,Afghanistan,22008,Gross Domestic Product,6119,Value US$ per capita,US$,154.957138,157.975357,139.756605,140.616194,166.095029,182.813796,194.202472,217.513678,241.579792,270.729453,273.035141,260.216148,266.302169,271.835860,276.059517,278.975344,282.961677,257.118767,233.594278,268.901352,286.772753,255.857628,237.803353,179.839036,100.444869,152.221868,141.607370,151.085927,148.706776,106.946309,160.829727,166.541981,183.247028,199.698828,217.921744,242.477079,268.781382,347.305373,369.266275,408.353930,503.636606,576.101770,6.141096e+02,6.080586e+02,5.858627e+02,5.437689e+02,5.092712e+02,5.206164e+02,4.955043e+02,4.969406e+02,5.084537e+02
3,2,'004,Afghanistan,22008,Gross Domestic Product,6183,"Value Local Currency, 2015 prices",millions,640024.694809,638260.085798,556498.281260,545260.592016,571963.541311,606538.115012,640652.358105,622700.035211,650881.544583,647761.511702,625359.636217,630423.153215,643414.185241,670981.813064,687706.446508,691900.378533,708420.513683,656098.152210,598661.464479,554676.102558,532223.150831,483512.600665,476587.229752,385407.968239,296737.925985,387337.309453,401148.285358,380405.169744,362609.298241,345273.395382,326789.905499,308373.050408,458140.931411,530558.854216,545734.797948,586710.864491,636952.631554,781177.101080,772544.956581,856508.039841,901472.494035,962434.513050,1.055821e+06,1.126041e+06,1.160649e+06,1.144181e+06,1.161900e+06,1.192655e+06,1.206839e+06,1.254046e+06,1.229783e+06
4,2,'004,Afghanistan,22008,Gross Domestic Product,6185,"Value US$ per capita, 2015 prices",US$,937.000000,910.000000,772.000000,736.000000,754.000000,782.000000,810.000000,773.000000,798.000000,790.000000,766.000000,783.000000,817.000000,875.000000,922.000000,948.000000,987.000000,925.000000,843.000000,764.000000,701.000000,595.000000,538.000000,399.000000,284.000000,350.000000,348.000000,321.000000,300.000000,280.000000,257.000000,233.000000,332.000000,366.000000,361.000000,374.000000,394.000000,471.000000,456.000000,493.000000,505.000000,523.000000,5.540000e+02,5.710000e+02,5.690000e+02,5.440000e+02,5.370000e+02,5.370000e+02,5.310000e+02,5.390000e+02,5.170000e+02

In [27]:
df = df[df['Element'].isin(['Value US$', 'Value US$ per capita', 'Annual growth US$, 2015 prices', 'Annual growth US$ per capita, 2015 prices'])]

In [28]:
df.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020
1,2,'004,Afghanistan,22008,Gross Domestic Product,6110,Value US$,millions,1731.435587,1812.837521,1647.900178,1702.716294,2061.729287,2319.753506,2513.580659,2864.939207,3222.963833,3630.767856,3646.796868,3427.482014,3430.645143,3408.204613,3369.110951,3330.465681,3320.888887,2983.743471,2713.899488,3191.557068,3559.511736,3402.654940,3444.711414,2844.442641,1715.169169,2756.838036,2669.785634,2924.589326,2935.139404,2157.197316,3342.034168,3598.470576,4141.523943,4729.042179,5388.482107,6220.574147,7104.711445,9412.161765,10236.901594,11595.133469,14698.889678,17350.694945,19136.499341,19621.802455,19550.702567,18713.048410,18019.558182,18896.352021,18418.848300,18904.490263,19793.262413
2,2,'004,Afghanistan,22008,Gross Domestic Product,6119,Value US$ per capita,US$,154.957138,157.975357,139.756605,140.616194,166.095029,182.813796,194.202472,217.513678,241.579792,270.729453,273.035141,260.216148,266.302169,271.835860,276.059517,278.975344,282.961677,257.118767,233.594278,268.901352,286.772753,255.857628,237.803353,179.839036,100.444869,152.221868,141.607370,151.085927,148.706776,106.946309,160.829727,166.541981,183.247028,199.698828,217.921744,242.477079,268.781382,347.305373,369.266275,408.353930,503.636606,576.101770,614.109574,608.058642,585.862673,543.768940,509.271172,520.616409,495.504343,496.940553,508.453722
10,2,'004,Afghanistan,22008,Gross Domestic Product,6182,"Annual growth US$, 2015 prices",%,NaN,-0.275710,-12.810108,-2.019357,4.897282,6.044891,5.624419,-2.802194,4.525696,-0.479355,-3.458352,0.809697,2.060684,4.284585,2.492561,0.609843,2.387646,-7.385777,-8.754283,-7.347285,-4.047939,-9.152279,-1.432304,-19.131705,-23.006800,30.531784,3.565620,-5.170935,-4.678136,-4.780877,-5.353291,-5.635687,48.567111,15.806910,2.860370,7.508421,8.563292,22.642888,-1.105018,10.868375,5.249741,6.762494,9.703175,6.650733,3.073402,-1.418885,1.548655,2.647003,1.189228,3.911603,-1.934778
11,2,'004,Afghanistan,22008,Gross Domestic Product,61820,"Annual growth US$ per capita, 2015 prices",%,NaN,-2.881537,-15.164835,-4.663212,2.445652,3.713528,3.580563,-4.567901,3.234153,-1.002506,-3.037975,2.219321,4.342273,7.099143,5.371429,2.819957,4.113924,-6.281662,-8.864865,-9.371293,-8.246073,-15.121255,-9.579832,-25.836431,-28.822055,23.239437,-0.571429,-7.758621,-6.542056,-6.666667,-8.214286,-9.338521,42.489270,10.240964,-1.366120,3.601108,5.347594,19.543147,-3.184713,8.114035,2.434077,3.564356,5.927342,3.068592,-0.350263,-4.393673,-1.286765,0.000000,-1.117318,1.506591,-4.081633
57,3,'008,Albania,22008,Gross Domestic Product,6110,Value US$,millions,2265.577056,2330.584860,2397.526448,2466.543461,2537.015817,2610.110369,2685.745678,2760.746397,2842.275926,2372.305641,2141.837051,2215.474766,2280.424885,2305.384485,2275.736342,2324.414456,2397.086883,2378.194810,2460.399974,2940.586487,2145.751209,1597.139589,1516.132824,1700.439125,1880.950821,2392.764887,3199.642024,2224.654241,2554.868837,3221.670165,3487.586302,3926.887597,4355.865889,5561.459461,7177.030365,8052.079314,8896.076004,10677.322220,12881.352058,12044.210390,11926.948284,12890.873323,12319.779604,12776.280738,13228.240079,11386.924853,11861.356451,13019.729856,15156.439968,15400.237155,14909.619335

In [29]:
#Save the transformed dataset

In [30]:
df.to_csv('../data/gdp_clean.csv')

In [31]:
df['Area'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Central African Republic', 'Chad',
       'Chile', 'China', 'China, Hong Kong SAR', 'China, Macao SAR',
       'China, mainland', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba', 'Curaçao',
       'Cyprus', 'Czechia', 'Czechoslovakia',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Ethiopia PDR', 'Fiji', 'Finland',
       'France', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic",
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (Federated States of)', 'Monaco', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'Netherlands Antilles (former)', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway',
       'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'Romania', 'Russian Federation', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Sudan (former)', 'Suriname',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan',
       'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Türkiye', 'Turkmenistan', 'Turks and Caicos Islands',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'USSR', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Yemen Ar Rp', 'Yemen Dem', 'Yugoslav SFR', 'Zambia', 'Zimbabwe',
       'World', 'Africa', 'Eastern Africa', 'Middle Africa',
       'Northern Africa', 'Southern Africa', 'Western Africa', 'Americas',
       'Northern America', 'Central America', 'Caribbean',
       'South America', 'Asia', 'Central Asia', 'Eastern Asia',
       'Southern Asia', 'South-eastern Asia', 'Western Asia', 'Europe',
       'Eastern Europe', 'Northern Europe', 'Southern Europe',
       'Western Europe', 'Oceania', 'Australia and New Zealand',
       'Melanesia', 'Micronesia', 'Polynesia', 'European Union (27)',
       'Least Developed Countries', 'Land Locked Developing Countries',
       'Small Island Developing States',
       'Low Income Food Deficit Countries',
       'Net Food Importing Developing Countries'], dtype=object)

In [50]:
df_columns = df.columns.str.replace('Y', '')
df_columns

Index(['Area Code', 'Area Code (M49)', 'Area', 'Item Code', 'Item',
       'Element Code', 'Element', 'Unit', '1970', '1971', '1972', '1973',
       '1974', '1975', '1976', '1977', '1978', '1979', '1980', '1981', '1982',
       '1983', '1984', '1985', '1986', '1987', '1988', '1989', '1990', '1991',
       '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999', '2000',
       '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008', '2009',
       '2010', '2011', '2012', '2013', '2014', '2015', '2016', '2017', '2018',
       '2019', '2020'],
      dtype='object')

In [52]:
list_columns = list(df_columns)

In [54]:
df.set_axis(list_columns, axis= 1, inplace=True)
df.head()

C:\Users\raque\AppData\Local\Temp\ipykernel_7756\2105464021.py:1: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  df.set_axis(list_columns, axis= 1, inplace=True)

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020
1,2,'004,Afghanistan,22008,Gross Domestic Product,6110,Value US$,millions,1731.435587,1812.837521,1647.900178,1702.716294,2061.729287,2319.753506,2513.580659,2864.939207,3222.963833,3630.767856,3646.796868,3427.482014,3430.645143,3408.204613,3369.110951,3330.465681,3320.888887,2983.743471,2713.899488,3191.557068,3559.511736,3402.654940,3444.711414,2844.442641,1715.169169,2756.838036,2669.785634,2924.589326,2935.139404,2157.197316,3342.034168,3598.470576,4141.523943,4729.042179,5388.482107,6220.574147,7104.711445,9412.161765,10236.901594,11595.133469,14698.889678,17350.694945,19136.499341,19621.802455,19550.702567,18713.048410,18019.558182,18896.352021,18418.848300,18904.490263,19793.262413
2,2,'004,Afghanistan,22008,Gross Domestic Product,6119,Value US$ per capita,US$,154.957138,157.975357,139.756605,140.616194,166.095029,182.813796,194.202472,217.513678,241.579792,270.729453,273.035141,260.216148,266.302169,271.835860,276.059517,278.975344,282.961677,257.118767,233.594278,268.901352,286.772753,255.857628,237.803353,179.839036,100.444869,152.221868,141.607370,151.085927,148.706776,106.946309,160.829727,166.541981,183.247028,199.698828,217.921744,242.477079,268.781382,347.305373,369.266275,408.353930,503.636606,576.101770,614.109574,608.058642,585.862673,543.768940,509.271172,520.616409,495.504343,496.940553,508.453722
10,2,'004,Afghanistan,22008,Gross Domestic Product,6182,"Annual growth US$, 2015 prices",%,NaN,-0.275710,-12.810108,-2.019357,4.897282,6.044891,5.624419,-2.802194,4.525696,-0.479355,-3.458352,0.809697,2.060684,4.284585,2.492561,0.609843,2.387646,-7.385777,-8.754283,-7.347285,-4.047939,-9.152279,-1.432304,-19.131705,-23.006800,30.531784,3.565620,-5.170935,-4.678136,-4.780877,-5.353291,-5.635687,48.567111,15.806910,2.860370,7.508421,8.563292,22.642888,-1.105018,10.868375,5.249741,6.762494,9.703175,6.650733,3.073402,-1.418885,1.548655,2.647003,1.189228,3.911603,-1.934778
11,2,'004,Afghanistan,22008,Gross Domestic Product,61820,"Annual growth US$ per capita, 2015 prices",%,NaN,-2.881537,-15.164835,-4.663212,2.445652,3.713528,3.580563,-4.567901,3.234153,-1.002506,-3.037975,2.219321,4.342273,7.099143,5.371429,2.819957,4.113924,-6.281662,-8.864865,-9.371293,-8.246073,-15.121255,-9.579832,-25.836431,-28.822055,23.239437,-0.571429,-7.758621,-6.542056,-6.666667,-8.214286,-9.338521,42.489270,10.240964,-1.366120,3.601108,5.347594,19.543147,-3.184713,8.114035,2.434077,3.564356,5.927342,3.068592,-0.350263,-4.393673,-1.286765,0.000000,-1.117318,1.506591,-4.081633
57,3,'008,Albania,22008,Gross Domestic Product,6110,Value US$,millions,2265.577056,2330.584860,2397.526448,2466.543461,2537.015817,2610.110369,2685.745678,2760.746397,2842.275926,2372.305641,2141.837051,2215.474766,2280.424885,2305.384485,2275.736342,2324.414456,2397.086883,2378.194810,2460.399974,2940.586487,2145.751209,1597.139589,1516.132824,1700.439125,1880.950821,2392.764887,3199.642024,2224.654241,2554.868837,3221.670165,3487.586302,3926.887597,4355.865889,5561.459461,7177.030365,8052.079314,8896.076004,10677.322220,12881.352058,12044.210390,11926.948284,12890.873323,12319.779604,12776.280738,13228.240079,11386.924853,11861.356451,13019.729856,15156.439968,15400.237155,14909.619335

In [55]:
df.to_csv('../data/gdp_clean.csv')

## Emissions dataset ##

In [108]:
em_raw = pd.read_csv('../data/FAOSTAT_emissions.csv', encoding = 'latin')

C:\Users\raque\AppData\Local\Temp\ipykernel_7756\50326155.py:1: DtypeWarning: Columns (99,102,105,108,111,114,117,120,123,126,129,132,135,138,141,144,147,150,153,156,159,162,165,168,171,174,177,180,183,186,189,191) have mixed types. Specify dtype option on import or set low_memory=False.
  em_raw = pd.read_csv('../data/FAOSTAT_emissions.csv', encoding = 'latin')

In [109]:
em_raw.head()
em_raw['Area'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belgium-Luxembourg', 'Belize', 'Benin', 'Bermuda',
       'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Central African Republic', 'Chad',
       'Channel Islands', 'Chile', 'China', 'China, Hong Kong SAR',
       'China, Macao SAR', 'China, mainland', 'China, Taiwan Province of',
       'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica',
       "Côte d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
       'Czechoslovakia', "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Ethiopia PDR',
       'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji', 'Finland',
       'France', 'French Guyana', 'French Polynesia', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland',
       'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Isle of Man',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
       'Mayotte', 'Mexico', 'Micronesia (Federated States of)', 'Monaco',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'Netherlands Antilles (former)', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island',
       'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Oman',
       'Pacific Islands Trust Territory', 'Pakistan', 'Palau',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico',
       'Qatar', 'Republic of Korea', 'Republic of Moldova', 'Réunion',
       'Romania', 'Russian Federation', 'Rwanda',
       'Saint Helena, Ascension and Tristan da Cunha',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Serbia and Montenegro', 'Seychelles',
       'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Sudan (former)', 'Suriname',
       'Svalbard and Jan Mayen Islands', 'Sweden', 'Switzerland',
       'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'Timor-Leste',
       'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Türkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu',
       'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'United States Virgin Islands', 'Uruguay', 'USSR', 'Uzbekistan',
       'Vanuatu', 'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Wallis and Futuna Islands', 'Western Sahara', 'Yemen',
       'Yugoslav SFR', 'Zambia', 'Zimbabwe', 'World', 'Africa',
       'Eastern Africa', 'Middle Africa', 'Northern Africa',
       'Southern Africa', 'Western Africa', 'Americas',
       'Northern America', 'Central America', 'Caribbean',
       'South America', 'Asia', 'Central Asia', 'Eastern Asia',
       'Southern Asia', 'South-eastern Asia', 'Western Asia', 'Europe',
       'Eastern Europe', 'Northern Europe', 'Southern Europe',
       'Western Europe', 'Oceania', 'Australia and New Zealand',
       'Melanesia', 'Micronesia', 'Polynesia', 'European Union (27)',
       'Least Developed Countries', 'Land Locked Developing Countries',
       'Small Island Developing States',
       'Low Income Food Deficit Countries',
       'Net Food Importing Developing Countries', 'Annex I countries',
       'Non-Annex I countries', 'OECD'], dtype=object)

In [110]:
#Clean the years
for col in em_raw.columns:
    if 'F' in col:
        em_raw.drop(col, axis=1, inplace=True)
    if 'N' in col:
        em_raw.drop(col, axis=1, inplace=True)
em_raw

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Source Code,Source,Unit,Y1961,Y1962,Y1963,Y1964,Y1965,Y1966,Y1967,Y1968,Y1969,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020,Y2021,Y2030,Y2050
0,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),3050,FAO TIER 1,kilotonnes,0.8762,0.8829,0.8236,0.8882,0.8978,0.8466,0.8783,0.8886,0.9123,0.8304,0.8093,0.9531,0.9725,0.9880,1.0138,1.0401,0.9566,0.9972,0.9533,0.9156,0.8766,0.8407,0.8065,0.7713,0.7319,0.6981,0.7706,0.6917,0.6601,6.334000e-01,6.454000e-01,6.054000e-01,7.110000e-01,7.456000e-01,7.511000e-01,7.672000e-01,8.511000e-01,8.854000e-01,7.624000e-01,5.200000e-01,5.267000e-01,8.200000e-01,9.988000e-01,8.225000e-01,1.182100e+00,1.027700e+00,1.242600e+00,8.869000e-01,1.392000e+00,1.274200e+00,1.032100e+00,1.372600e+00,1.401800e+00,1.458400e+00,1.242400e+00,1.194000e+00,1.061700e+00,8.988000e-01,1.217600e+00,1.317000e+00,NaN,1.533700e+00,1.938900e+00
1,2,'004,Afghanistan,5064,Crop Residues,7236,Indirect emissions (N2O),3050,FAO TIER 1,kilotonnes,0.1972,0.1987,0.1853,0.1998,0.2020,0.1905,0.1976,0.1999,0.2053,0.1868,0.1821,0.2145,0.2188,0.2223,0.2281,0.2340,0.2152,0.2244,0.2145,0.2060,0.1972,0.1892,0.1815,0.1735,0.1647,0.1571,0.1734,0.1556,0.1485,1.425000e-01,1.452000e-01,1.362000e-01,1.600000e-01,1.678000e-01,1.690000e-01,1.726000e-01,1.915000e-01,1.992000e-01,1.715000e-01,1.170000e-01,1.185000e-01,1.845000e-01,2.247000e-01,1.851000e-01,2.660000e-01,2.312000e-01,2.796000e-01,1.996000e-01,3.132000e-01,2.867000e-01,2.322000e-01,3.088000e-01,3.154000e-01,3.281000e-01,2.795000e-01,2.687000e-01,2.389000e-01,2.022000e-01,2.740000e-01,2.963000e-01,NaN,3.451000e-01,4.362000e-01
2,2,'004,Afghanistan,5064,Crop Residues,7230,Emissions (N2O),3050,FAO TIER 1,kilotonnes,1.0734,1.0816,1.0089,1.0880,1.0998,1.0371,1.0759,1.0885,1.1176,1.0172,0.9914,1.1676,1.1913,1.2103,1.2419,1.2741,1.1718,1.2215,1.1678,1.1216,1.0738,1.0299,0.9880,0.9448,0.8965,0.8551,0.9439,0.8473,0.8086,7.759000e-01,7.906000e-01,7.416000e-01,8.710000e-01,9.134000e-01,9.201000e-01,9.398000e-01,1.042600e+00,1.084700e+00,9.340000e-01,6.370000e-01,6.452000e-01,1.004500e+00,1.223500e+00,1.007500e+00,1.448100e+00,1.258900e+00,1.522200e+00,1.086500e+00,1.705100e+00,1.560900e+00,1.264300e+00,1.681500e+00,1.717300e+00,1.786500e+00,1.522000e+00,1.462700e+00,1.300500e+00,1.101100e+00,1.491600e+00,1.613300e+00,NaN,1.878800e+00,2.375100e+00
3,2,'004,Afghanistan,5064,Crop Residues,724313,Emissions (CO2eq) from N2O (AR5),3050,FAO TIER 1,kilotonnes,284.4486,286.6192,267.3466,288.3212,291.4406,274.8304,285.1026,288.4483,296.1556,269.5529,262.7338,309.4116,315.6948,320.7274,329.1046,337.6487,310.5341,323.7090,309.4714,297.2257,284.5502,272.9278,261.8147,250.3726,237.5808,226.6047,250.1406,224.5390,214.2788,2.056077e+02,2.094971e+02,1.965341e+02,2.308175e+02,2.420494e+02,2.438152e+02,2.490364e+02,2.762940e+02,2.874346e+02,2.474980e+02,1.688070e+02,1.709884e+02,2.661975e+02,3.242195e+02,2.669995e+02,3.837498e+02,3.336093e+02,4.033749e+02,2.879099e+02,4.518647e+02,4.136467e+02,3.350379e+02,4.455958e+02,4.550727e+02,4.734174e+02,4.033181e+02,3.876130e+02,3.446447e+02,2.917838e+02,3.952689e+02,4.275284e+02,NaN,4.978929e+02,6.294047e+02
4,2,'004,Afghanistan,5064,Crop Residues,723113,Emissions (CO2eq) (AR5),3050,FAO TIER 1,kilotonnes,284.4486,286.6192,267.3466,288.3212,291.4406,274.8304,285.1026,288.4483,296.1556,269.5529,262.7338,309.4116,315.6948,320.7274,329.1046,337.6487,310.5341,323.7090,309.4714,297.2257,284.5502,272.9278,261.8147,250.3726,237.5808,226.6047,250.1406,224.5390,214.2788,2.056077e+02,2.094971e+02,1.965341e+02,2.308175e+02,2.420494e+02,2.438152e+02,2.490364e+02,2.762940e+02,2.874346e+02,2.474980e+02,1.688070e+02,1.709884e+02,2.661975e+02,3.242195e+02,2.669995e+02,3.837498e+02,3.336093e+02,4.033749e+02,2.879099e+02,4.518647e+02,4.136467e+02,3.350379e+02,4.455958e+02,4.550727e+02,4.734174e+02,4.033181e+02,3.876130e+02,3.446447e+02,2.917838e+02,3.952689e+02,4.275284e+02,NaN,4.978929e+02,6.294047e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58760,5873,'198,OECD,6829,All sectors without LULUCF,7273,Emissions (CO2),3050,FAO TIER 1,kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.168868e+07,1.167353e+07,1.179066e+07,1.208670e+07,1.224481e+07,1.239817e+07,1.274622e+07,1.289772e+07,1.289722e+07,1.301006e+07,1.334328e+07,1.326305e+07,1.332979e+07,1.352237e+07,1.366651e+07,1.369481e+07,1.369710e+07,1.379770e+07,1.358338e+07,1.273838e+07,1.311391e+07,1.289801e+07,1.270146e+07,1.274243e+07,1.261664e+07,1.253301e+07,1.241227e+07,1.243658e+07,1.254684e+07,1.217070e+07,1.088919e+07,NaN,NaN,NaN
58761,5873,'198,OECD,6829,All sectors without LULUCF,717815,Emissions (CO2eq) from F-gases (AR5),3050,FAO TIER 1,kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.317321e+05,2.448633e+05,2.443795e+05,2.599735e+05,2.697196e+05,3.035266e+05,3.224641e+05,3.352787e+05,3.613529e+05,3.841316e+05,3.941893e+05,3.882647e+05,4.176531e+05,4.392191e+05,4.672796e+05,5.080909e+05,5.511406e+05,5.902422e+05,6.271651e+05,6.774160e+05,7.641415e+05,7.759070e+05,7.826597e+05,8.006688e+05,8.326775e+05,8.546258e+05,8.741566e+05,8.884415e+05,9.049044e+05,9.172806e+05,9.208261e+05,NaN,NaN,NaN
58762,5873,'198,OECD,6829,All sectors without LULUCF,724413,Emissions (CO2eq) from CH4 (AR5),3050,FAO TIER 1,kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.211414e+06,2.193405e+06,2.188266e+06,2.202112e+06,2.201626e+06,2.197011e+06,2.191662e+06,2.193442e+06,2.159460e+06,2.142911e+06,2.145052e+06,2.126567e+06,2.093083e+06,2.038232e+06,2.047953e+06,2.008645e+06,2.039932e+06,2.035230e+06,2.016547e+06,1.965772e+06,1.931536e+06,1.980459e+06,1.971959e+06,1.922551e+06,1.934854e+06,1.924370e+06,1.880327e+06,1.915982e+06,1.923635e+06,1.882769e+06,1.825476e+06,NaN,7.887809e+05,7.860732e+05
58763,5873,'198,OECD,6829,All sectors without LULUCF,724313,Emissions (CO2eq) from N2O (AR5),3050,FAO TIER 1,kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.206222e+05,8.111995e+05,8.174218e+05,8.280263e+05,8.504114e+05,8.636051e+05,8.801739e+05,8.787657e+05,8.472212e+05,8.475524e+05,8.535273e+05,8.496131e+05,8.400758e+05,8.124412e+05,8.328157e+05,8.123489e+05,8.257754e+05,8.312711e+05,7.887649e+05,7.878419e+05,7.864163e+05,8.344119e+05,8.490201e+05,8.204159e+05,8.325680e+05,8.289014e+05,8.218071e+05,8.400423e+05,8.349622e+05,8.118189e+05,8.009744e+05,NaN,4.154914e+05,4.299135e+05
58764,5873,'198,OECD,6829,All sectors without LULUCF,723113,Emissions (CO2eq) (AR5),3050,FAO TIER 1,kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.495245e+07,1.492300e+07,1.504073e+07,1.537681e+07,1.556657e+07,1.576232e+07,1.614052e+07,1.630521e+07,1.626525e+07,1.638466e+07,1.673605e+07,1.662750e+07,1.668060e+07,1.681226e+07,1.701456e+07,1.702390e+07,1.711395e+07,1.725445e+07,1.701586e+07,1.616941e+07,1.659600e+07,1.648879e+07,1.630510e+07,1.628606e+07,1.621674e+07,1.614090e+07,1.598856e+07,1.608104e+07,1.621034e+07,1.578256e+07,1.443647e+07,NaN,1.204272e+06,1.215987e+06

In [111]:
em_raw.columns.str.replace('Y', '')

Index(['Area Code', 'Area Code (M49)', 'Area', 'Item Code', 'Item',
       'Element Code', 'Element', 'Source Code', 'Source', 'Unit', '1961',
       '1962', '1963', '1964', '1965', '1966', '1967', '1968', '1969', '1970',
       '1971', '1972', '1973', '1974', '1975', '1976', '1977', '1978', '1979',
       '1980', '1981', '1982', '1983', '1984', '1985', '1986', '1987', '1988',
       '1989', '1990', '1991', '1992', '1993', '1994', '1995', '1996', '1997',
       '1998', '1999', '2000', '2001', '2002', '2003', '2004', '2005', '2006',
       '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',
       '2016', '2017', '2018', '2019', '2020', '2021', '2030', '2050'],
      dtype='object')

In [112]:
list_columns = list(em_raw_columns)

In [113]:
em_raw.set_axis(list_columns, axis= 1, inplace=True)
em_raw.head()

C:\Users\raque\AppData\Local\Temp\ipykernel_7756\4151740144.py:1: FutureWarning: DataFrame.set_axis 'inplace' keyword is deprecated and will be removed in a future version. Use `obj = obj.set_axis(..., copy=False)` instead
  em_raw.set_axis(list_columns, axis= 1, inplace=True)

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Source Code,Source,Unit,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2030,2050
0,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),3050,FAO TIER 1,kilotonnes,0.8762,0.8829,0.8236,0.8882,0.8978,0.8466,0.8783,0.8886,0.9123,0.8304,0.8093,0.9531,0.9725,0.9880,1.0138,1.0401,0.9566,0.9972,0.9533,0.9156,0.8766,0.8407,0.8065,0.7713,0.7319,0.6981,0.7706,0.6917,0.6601,0.6334,0.6454,0.6054,0.7110,0.7456,0.7511,0.7672,0.8511,0.8854,0.7624,0.520,0.5267,0.8200,0.9988,0.8225,1.1821,1.0277,1.2426,0.8869,1.3920,1.2742,1.0321,1.3726,1.4018,1.4584,1.2424,1.1940,1.0617,0.8988,1.2176,1.3170,NaN,1.5337,1.9389
1,2,'004,Afghanistan,5064,Crop Residues,7236,Indirect emissions (N2O),3050,FAO TIER 1,kilotonnes,0.1972,0.1987,0.1853,0.1998,0.2020,0.1905,0.1976,0.1999,0.2053,0.1868,0.1821,0.2145,0.2188,0.2223,0.2281,0.2340,0.2152,0.2244,0.2145,0.2060,0.1972,0.1892,0.1815,0.1735,0.1647,0.1571,0.1734,0.1556,0.1485,0.1425,0.1452,0.1362,0.1600,0.1678,0.1690,0.1726,0.1915,0.1992,0.1715,0.117,0.1185,0.1845,0.2247,0.1851,0.2660,0.2312,0.2796,0.1996,0.3132,0.2867,0.2322,0.3088,0.3154,0.3281,0.2795,0.2687,0.2389,0.2022,0.2740,0.2963,NaN,0.3451,0.4362
2,2,'004,Afghanistan,5064,Crop Residues,7230,Emissions (N2O),3050,FAO TIER 1,kilotonnes,1.0734,1.0816,1.0089,1.0880,1.0998,1.0371,1.0759,1.0885,1.1176,1.0172,0.9914,1.1676,1.1913,1.2103,1.2419,1.2741,1.1718,1.2215,1.1678,1.1216,1.0738,1.0299,0.9880,0.9448,0.8965,0.8551,0.9439,0.8473,0.8086,0.7759,0.7906,0.7416,0.8710,0.9134,0.9201,0.9398,1.0426,1.0847,0.9340,0.637,0.6452,1.0045,1.2235,1.0075,1.4481,1.2589,1.5222,1.0865,1.7051,1.5609,1.2643,1.6815,1.7173,1.7865,1.5220,1.4627,1.3005,1.1011,1.4916,1.6133,NaN,1.8788,2.3751
3,2,'004,Afghanistan,5064,Crop Residues,724313,Emissions (CO2eq) from N2O (AR5),3050,FAO TIER 1,kilotonnes,284.4486,286.6192,267.3466,288.3212,291.4406,274.8304,285.1026,288.4483,296.1556,269.5529,262.7338,309.4116,315.6948,320.7274,329.1046,337.6487,310.5341,323.7090,309.4714,297.2257,284.5502,272.9278,261.8147,250.3726,237.5808,226.6047,250.1406,224.5390,214.2788,205.6077,209.4971,196.5341,230.8175,242.0494,243.8152,249.0364,276.2940,287.4346,247.4980,168.807,170.9884,266.1975,324.2195,266.9995,383.7498,333.6093,403.3749,287.9099,451.8647,413.6467,335.0379,445.5958,455.0727,473.4174,403.3181,387.6130,344.6447,291.7838,395.2689,427.5284,NaN,497.8929,629.4047
4,2,'004,Afghanistan,5064,Crop Residues,723113,Emissions (CO2eq) (AR5),3050,FAO TIER 1,kilotonnes,284.4486,286.6192,267.3466,288.3212,291.4406,274.8304,285.1026,288.4483,296.1556,269.5529,262.7338,309.4116,315.6948,320.7274,329.1046,337.6487,310.5341,323.7090,309.4714,297.2257,284.5502,272.9278,261.8147,250.3726,237.5808,226.6047,250.1406,224.5390,214.2788,205.6077,209.4971,196.5341,230.8175,242.0494,243.8152,249.0364,276.2940,287.4346,247.4980,168.807,170.9884,266.1975,324.2195,266.9995,383.7498,333.6093,403.3749,287.9099,451.8647,413.6467,335.0379,445.5958,455.0727,473.4174,403.3181,387.6130,344.6447,291.7838,395.2689,427.5284,NaN,497.8929,629.4047

In [114]:
em = em_raw.drop(['Element Code', 'Area Code', 'Source Code', 'Area Code (M49)', 'Source'], axis=1)
em.head()
em['Element'].unique()

array(['Direct emissions (N2O)', 'Indirect emissions (N2O)',
       'Emissions (N2O)', 'Emissions (CO2eq) from N2O (AR5)',
       'Emissions (CO2eq) (AR5)', 'Emissions (CH4)',
       'Emissions (CO2eq) from CH4 (AR5)', 'Emissions (CO2)',
       'Emissions (CO2eq) from F-gases (AR5)'], dtype=object)

In [115]:
#from this dataset we only take the values when Element == "Emissions (CH4)", "Emissions (N20)", "Emissions (CO2)"
em = em[em['Element'].isin(['Emissions (N2O)', 'Emissions (CH4)', 'Emissions (CO2)'])]
em.head()

,Area,Item Code,Item,Element,Unit,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2030,2050
2,Afghanistan,5064,Crop Residues,Emissions (N2O),kilotonnes,1.0734,1.0816,1.0089,1.0880,1.0998,1.0371,1.0759,1.0885,1.1176,1.0172,0.9914,1.1676,1.1913,1.2103,1.2419,1.2741,1.1718,1.2215,1.1678,1.1216,1.0738,1.0299,0.9880,0.9448,0.8965,0.8551,0.9439,0.8473,0.8086,0.7759,0.7906,0.7416,0.8710,0.9134,0.9201,0.9398,1.0426,1.0847,0.9340,0.6370,0.6452,1.0045,1.2235,1.0075,1.4481,1.2589,1.5222,1.0865,1.7051,1.5609,1.2643,1.6815,1.7173,1.7865,1.5220,1.4627,1.3005,1.1011,1.4916,1.6133,NaN,1.8788,2.3751
5,Afghanistan,5060,Rice Cultivation,Emissions (CH4),kilotonnes,29.4000,29.4000,29.4000,30.8000,30.8000,31.0800,28.8400,28.8400,28.8400,28.2800,28.0000,29.4000,29.4000,29.4000,29.4000,29.4000,29.4000,29.4000,28.8400,26.7400,24.3600,23.1700,21.7000,20.8600,19.7400,21.0000,22.6800,25.2000,23.8000,24.5000,24.2200,24.5000,24.5000,25.2000,23.8000,24.5000,25.2000,25.2000,19.6000,18.2000,16.9400,18.9000,20.3000,27.3000,22.4000,22.4000,23.8000,26.6000,28.0000,29.1200,29.4000,28.7000,28.7000,30.8000,22.9600,16.6600,15.3233,16.4555,17.8542,20.6577,NaN,32.3685,41.3331
8,Afghanistan,5066,Burning - Crop residues,Emissions (CH4),kilotonnes,4.0734,4.1933,4.1933,4.2260,4.2150,4.2169,3.9679,3.7314,3.7798,3.8748,4.1894,4.6862,4.0719,4.0644,4.1637,4.1574,4.1475,4.1561,3.9218,3.6997,3.5589,3.4257,3.2522,3.1384,2.9808,2.8837,2.9944,2.8052,2.7255,2.6977,2.7606,2.5314,3.0714,3.2408,3.2016,3.0714,3.1047,3.1717,2.8326,2.6471,2.3205,2.3553,3.4017,3.0089,3.4752,3.2535,3.2921,2.9674,3.4614,3.3507,3.2219,3.4035,3.4506,3.5413,2.9452,3.0734,2.7997,2.1390,2.9693,3.4826,NaN,3.4935,3.4857
9,Afghanistan,5066,Burning - Crop residues,Emissions (CH4),kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0700,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Afghanistan,5066,Burning - Crop residues,Emissions (N2O),kilotonnes,0.1056,0.1087,0.1087,0.1096,0.1093,0.1093,0.1029,0.0967,0.0980,0.1005,0.1086,0.1215,0.1056,0.1054,0.1079,0.1078,0.1075,0.1078,0.1017,0.0959,0.0923,0.0888,0.0843,0.0814,0.0773,0.0748,0.0776,0.0727,0.0707,0.0699,0.0716,0.0656,0.0796,0.0840,0.0830,0.0796,0.0805,0.0822,0.0734,0.0686,0.0602,0.0611,0.0882,0.0780,0.0901,0.0844,0.0854,0.0769,0.0897,0.0869,0.0835,0.0882,0.0895,0.0918,0.0764,0.0797,0.0726,0.0555,0.0770,0.0903,NaN,0.0906,0.0904

In [116]:
em['Item'].unique()

array(['Crop Residues', 'Rice Cultivation', 'Burning - Crop residues',
       'Enteric Fermentation', 'Manure Management',
       'Manure left on Pasture', 'Manure applied to Soils',
       'Synthetic Fertilizers', 'Drained organic soils (CO2)',
       'Drained organic soils (N2O)', 'On-farm energy use', 'Forestland',
       'Net Forest conversion', 'Savanna fires', 'Fires in organic soils',
       'Forest fires', 'Fires in humid tropical forests',
       'Waste - agri-food systems', 'Fertilizers Manufacturing',
       'On-farm electricity use', 'Food Processing', 'Food Packaging',
       'Food Retail', 'Food Household Consumption', 'Food Transport',
       'Energy', 'IPPU', 'Waste', 'Other', 'Farm-gate emissions',
       'Land Use change', 'Emissions on agricultural land',
       'Pre- and post- production', 'Agri-food systems',
       'IPCC Agriculture', 'Agricultural Soils', 'LULUCF', 'AFOLU',
       'All sectors with LULUCF', 'All sectors without LULUCF',
       'International bunkers'], dtype=object)

In [118]:
em = em[em['Item'].isin(['Forestland', 'Net Forest conversion', 'All sectors with LULUCF', 'All sectors without LULUCF'])]
em.head()

,Area,Item Code,Item,Element,Unit,1961,1962,1963,1964,1965,1966,1967,1968,1969,1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2030,2050
59,Afghanistan,6751,Forestland,Emissions (CO2),kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2388.8030,-2388.8030,-2388.8030,-2388.8030,-2388.8030,-2388.8030,-2388.8030,-2388.8030,-2388.8030,-2388.8030,-2388.8030,121.9016,121.9016,121.9016,121.9016,121.9016,121.9016,121.9016,121.9016,121.9016,121.9016,-246.2191,-246.2191,-246.2191,-246.2191,-246.2191,154.6574,154.6574,154.6574,154.6574,154.6574,NaN,NaN,NaN
61,Afghanistan,6750,Net Forest conversion,Emissions (CO2),kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN,NaN
212,Afghanistan,6825,All sectors with LULUCF,Emissions (CH4),kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,283.4658,296.7285,302.0717,309.1496,323.3615,342.3478,378.7676,408.8165,432.2855,466.2228,419.1023,371.2675,447.8971,463.6655,465.8062,477.8682,487.9664,501.3724,546.1793,562.1262,631.3810,652.3301,648.2713,648.8900,663.5479,634.5774,629.3893,624.3983,635.7765,638.0114,662.7644,NaN,516.8208,683.7073
213,Afghanistan,6825,All sectors with LULUCF,Emissions (N2O),kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.5760,9.8467,9.6522,9.7923,9.2279,9.6663,10.4915,11.5397,12.5119,13.4194,11.6462,10.2895,11.9045,12.3870,12.3179,12.8563,12.3056,12.0883,13.1119,14.1314,15.6135,16.3091,16.3303,16.3723,17.3372,17.2410,17.0810,17.9014,15.9129,15.9893,16.7350,NaN,18.5334,25.7772
214,Afghanistan,6825,All sectors with LULUCF,Emissions (CO2),kilotonnes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,380.1970,217.1970,-827.8030,-898.8030,-967.8030,-1025.8030,-1104.8030,-1185.8030,-1244.8030,-1460.8030,-1474.8030,1066.9016,1347.9016,1478.9016,1187.9016,1610.9016,1947.9016,2579.9016,4516.9016,7068.9016,8751.9016,12143.7809,10317.7809,8554.7809,7853.7809,7937.7809,7194.6574,8355.6574,8840.6574,9630.6574,9592.6574,NaN,NaN,NaN

In [119]:
em_raw['Area'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'American Samoa', 'Andorra',
       'Angola', 'Anguilla', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus',
       'Belgium', 'Belgium-Luxembourg', 'Belize', 'Benin', 'Bermuda',
       'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Central African Republic', 'Chad',
       'Channel Islands', 'Chile', 'China', 'China, Hong Kong SAR',
       'China, Macao SAR', 'China, mainland', 'China, Taiwan Province of',
       'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica',
       "Côte d'Ivoire", 'Croatia', 'Cuba', 'Cyprus', 'Czechia',
       'Czechoslovakia', "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Ethiopia PDR',
       'Falkland Islands (Malvinas)', 'Faroe Islands', 'Fiji', 'Finland',
       'France', 'French Guyana', 'French Polynesia', 'Gabon', 'Gambia',
       'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland',
       'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Isle of Man',
       'Israel', 'Italy', 'Jamaica', 'Japan', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kuwait', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Latvia', 'Lebanon', 'Lesotho',
       'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius',
       'Mayotte', 'Mexico', 'Micronesia (Federated States of)', 'Monaco',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'Netherlands Antilles (former)', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk Island',
       'North Macedonia', 'Northern Mariana Islands', 'Norway', 'Oman',
       'Pacific Islands Trust Territory', 'Pakistan', 'Palau',
       'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru',
       'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico',
       'Qatar', 'Republic of Korea', 'Republic of Moldova', 'Réunion',
       'Romania', 'Russian Federation', 'Rwanda',
       'Saint Helena, Ascension and Tristan da Cunha',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines',
       'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia',
       'Senegal', 'Serbia', 'Serbia and Montenegro', 'Seychelles',
       'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Sudan (former)', 'Suriname',
       'Svalbard and Jan Mayen Islands', 'Sweden', 'Switzerland',
       'Syrian Arab Republic', 'Tajikistan', 'Thailand', 'Timor-Leste',
       'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia',
       'Türkiye', 'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu',
       'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'United States Virgin Islands', 'Uruguay', 'USSR', 'Uzbekistan',
       'Vanuatu', 'Venezuela (Bolivarian Republic of)', 'Viet Nam',
       'Wallis and Futuna Islands', 'Western Sahara', 'Yemen',
       'Yugoslav SFR', 'Zambia', 'Zimbabwe', 'World', 'Africa',
       'Eastern Africa', 'Middle Africa', 'Northern Africa',
       'Southern Africa', 'Western Africa', 'Americas',
       'Northern America', 'Central America', 'Caribbean',
       'South America', 'Asia', 'Central Asia', 'Eastern Asia',
       'Southern Asia', 'South-eastern Asia', 'Western Asia', 'Europe',
       'Eastern Europe', 'Northern Europe', 'Southern Europe',
       'Western Europe', 'Oceania', 'Australia and New Zealand',
       'Melanesia', 'Micronesia', 'Polynesia', 'European Union (27)',
       'Least Developed Countries', 'Land Locked Developing Countries',
       'Small Island Developing States',
       'Low Income Food Deficit Countries',
       'Net Food Importing Developing Countries', 'Annex I countries',
       'Non-Annex I countries', 'OECD'], dtype=object)

In [120]:
df.to_csv('../data/emissions_clean.csv')