## GDP dataset ##

### Packages and dataset ###

In [2]:
#IMPORT NEEDED PACKAGES

import plotly.graph_objects as go
import plotly.express as px
import plotly.io as pio
import pandas as pd
import numpy as np
pd.options.display.max_columns = None

In [3]:
# READ RAW CSV
df_raw = pd.read_csv('../../Macro-Statistics_Key_Indicators/Macro-Statistics_Key_Indicators_E_All_Data.csv', encoding = 'latin')

### Exploring the data ###

In [4]:
df_raw.shape

(15799, 161)

In [5]:
df_raw.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1970,Y1970F,Y1970N,Y1971,Y1971F,Y1971N,Y1972,Y1972F,Y1972N,Y1973,Y1973F,Y1973N,Y1974,Y1974F,Y1974N,Y1975,Y1975F,Y1975N,Y1976,Y1976F,Y1976N,Y1977,Y1977F,Y1977N,Y1978,Y1978F,Y1978N,Y1979,Y1979F,Y1979N,Y1980,Y1980F,Y1980N,Y1981,Y1981F,Y1981N,Y1982,Y1982F,Y1982N,Y1983,Y1983F,Y1983N,Y1984,Y1984F,Y1984N,Y1985,Y1985F,Y1985N,Y1986,Y1986F,Y1986N,Y1987,Y1987F,Y1987N,Y1988,Y1988F,Y1988N,Y1989,Y1989F,Y1989N,Y1990,Y1990F,Y1990N,Y1991,Y1991F,Y1991N,Y1992,Y1992F,Y1992N,Y1993,Y1993F,Y1993N,Y1994,Y1994F,Y1994N,Y1995,Y1995F,Y1995N,Y1996,Y1996F,Y1996N,Y1997,Y1997F,Y1997N,Y1998,Y1998F,Y1998N,Y1999,Y1999F,Y1999N,Y2000,Y2000F,Y2000N,Y2001,Y2001F,Y2001N,Y2002,Y2002F,Y2002N,Y2003,Y2003F,Y2003N,Y2004,Y2004F,Y2004N,Y2005,Y2005F,Y2005N,Y2006,Y2006F,Y2006N,Y2007,Y2007F,Y2007N,Y2008,Y2008F,Y2008N,Y2009,Y2009F,Y2009N,Y2010,Y2010F,Y2010N,Y2011,Y2011F,Y2011N,Y2012,Y2012F,Y2012N,Y2013,Y2013F,Y2013N,Y2014,Y2014F,Y2014N,Y2015,Y2015F,Y2015N,Y2016,Y2016F,Y2016N,Y2017,Y2017F,Y2017N,Y2018,Y2018F,Y2018N,Y2019,Y2019F,Y2019N,Y2020,Y2020F,Y2020N
0,2,'004,Afghanistan,22008,Gross Domestic Product,6109,Value Local Currency,millions,77.911878,X,NaN,81.574837,X,NaN,74.152916,X,NaN,76.619555,X,NaN,92.774575,X,NaN,104.385259,X,NaN,113.107176,X,NaN,128.917758,X,NaN,145.028303,X,NaN,158.776212,X,NaN,160.930107,X,NaN,169.591475,X,NaN,173.589299,X,NaN,172.453817,X,NaN,170.475688,X,NaN,168.520249,X,NaN,168.035667,X,NaN,150.976242,X,NaN,137.322243,X,NaN,161.491528,X,NaN,180.109889,X,NaN,172.172997,X,NaN,174.301038,X,NaN,143.927675,X,NaN,729.118301,X,NaN,2297.365030,X,NaN,6674.524156,X,NaN,8773.855716,X,NaN,8805.572314,X,NaN,100567.527295,X,NaN,158270.632870,X,NaN,170927.404578,X,NaN,195740.846106,X,NaN,230601.118468,X,NaN,257813.610332,X,NaN,307884.813631,X,NaN,354705.069349,X,NaN,470250.593341,X,NaN,514400.361283,X,NaN,583525.091849,X,NaN,682799.599547,X,NaN,811093.070883,X,NaN,9.744573e+05,X,NaN,1.086606e+06,X,NaN,1.119229e+06,X,NaN,1.144181e+06,X,NaN,1.222917e+06,X,NaN,1.285460e+06,X,NaN,1.327690e+06,X,NaN,1.469596e+06,X,NaN,1.520390e+06,X,NaN
1,2,'004,Afghanistan,22008,Gross Domestic Product,6110,Value US$,millions,1731.435587,X,NaN,1812.837521,X,NaN,1647.900178,X,NaN,1702.716294,X,NaN,2061.729287,X,NaN,2319.753506,X,NaN,2513.580659,X,NaN,2864.939207,X,NaN,3222.963833,X,NaN,3630.767856,X,NaN,3646.796868,X,NaN,3427.482014,X,NaN,3430.645143,X,NaN,3408.204613,X,NaN,3369.110951,X,NaN,3330.465681,X,NaN,3320.888887,X,NaN,2983.743471,X,NaN,2713.899488,X,NaN,3191.557068,X,NaN,3559.511736,X,NaN,3402.654940,X,NaN,3444.711414,X,NaN,2844.442641,X,NaN,1715.169169,X,NaN,2756.838036,X,NaN,2669.785634,X,NaN,2924.589326,X,NaN,2935.139404,X,NaN,2157.197316,X,NaN,3342.034168,X,NaN,3598.470576,X,NaN,4141.523943,X,NaN,4729.042179,X,NaN,5388.482107,X,NaN,6220.574147,X,NaN,7104.711445,X,NaN,9412.161765,X,NaN,10236.901594,X,NaN,11595.133469,X,NaN,14698.889678,X,NaN,17350.694945,X,NaN,1.913650e+04,X,NaN,1.962180e+04,X,NaN,1.955070e+04,X,NaN,1.871305e+04,X,NaN,1.801956e+04,X,NaN,1.889635e+04,X,NaN,1.841885e+04,X,NaN,1.890449e+04,X,NaN,1.979326e+04,X,NaN
2,2,'004,Afghanistan,22008,Gross Domestic Product,6119,Value US$ per capita,US$,154.957138,X,NaN,157.975357,X,NaN,139.756605,X,NaN,140.616194,X,NaN,166.095029,X,NaN,182.813796,X,NaN,194.202472,X,NaN,217.513678,X,NaN,241.579792,X,NaN,270.729453,X,NaN,273.035141,X,NaN,260.216148,X,NaN,266.302169,X,NaN,271.835860,X,NaN,276.059517,X,NaN,278.975344,X,NaN,282.961677,X,NaN,257.118767,X,NaN,233.594278,X,NaN,268.901352,X,NaN,286.772753,X,NaN,255.857628,X,NaN,237.803353,X,NaN,179.839036,X,NaN,100.444869,X,NaN,152.221868,X,NaN,141.607370,X,NaN,151.085927,X,NaN,148.706776,X,NaN,106.946309,X,NaN,160.829727,X,NaN,166.541981,X,NaN,183.247028,X,NaN,199.698828,X,NaN,217.921744,X,NaN,242.477079,X,NaN,268.781382,X,NaN,347.305373,X,NaN,369.266275,X,NaN,408.353930,X,NaN,503.636606,X,NaN,576.101770,X,NaN,6.141096e+02,X,NaN,6.080586e+02,X,NaN,5.858627e+02,X,NaN,5.437689e+02,X,NaN,5.092712e+02,X,NaN,5.206164e+02,X,NaN,4.955043e+02,X,NaN,4.969406e+02,X,NaN,5.084537e+02,X,NaN
3,2,'004,Afghanistan,22008,Gross Domestic Product,6183,"Value Local Currency, 2015 prices",millions,640024.694809,X,NaN,638260.085798,X,NaN,556498.281260,X,NaN,545260.592016,X,NaN,571963.541311,X,NaN,606538.115012,X,NaN,640652.358105,X,NaN,622700.035211,X,NaN,650881.544583,X,NaN,647761.511702,X,NaN,625359.636217,X,NaN,630423.153215,X,NaN,643414.185241,X,NaN,670981.813064,X,NaN,687706.446508,X,NaN,691900.378533,X,NaN,708420.513683,X,NaN,656098.152210,X,NaN,598661.464479,X,NaN,554676.102558,X,NaN,532223.150831,X,NaN,483512.600665,X,NaN,476587.229752,X,NaN,385407.968239,X,NaN,296737.925985,X,NaN,387337.309453,X,NaN,401148.285358,X,NaN,380405.169744,X,NaN,362609.298241,X,NaN,345273.395382,X,NaN,326789.905499,X,NaN,308373.050408,X,NaN,458140.931411,X,NaN,530558.854216,X,NaN,545734.797948,X,NaN,586710.864491,X,NaN,636952.631554,X,NaN,781177.101080,X,NaN,772544.956581,X,NaN,856508.039841,X,NaN,901472.494035,X,NaN,962434.513050,X,NaN,1.055821e+06,X,NaN,1.126041e+06,X,NaN,1.160649e+06,X,NaN,1.144181e+06,X,NaN,1.161900e+06,X,NaN,1.192655e+06,X,NaN,1.206839e+06,X,NaN,1.254046e+06,X,NaN,1.229783e+06,X,NaN
4,2,'004,Afghanistan,22008,Gross Domestic Product,6185,"Value US$ per capita, 2015 prices",US$,937.000000,X,NaN,910.000000,X,NaN,772.000000,X,NaN,736.000000,X,NaN,754.000000,X,NaN,782.000000,X,NaN,810.000000,X,NaN,773.000000,X,NaN,798.000000,X,NaN,790.000000,X,NaN,766.000000,X,NaN,783.000000,X,NaN,817.000000,X,NaN,875.000000,X,NaN,922.000000,X,NaN,948.000000,X,NaN,987.000000,X,NaN,925.000000,X,NaN,843.000000,X,NaN,764.000000,X,NaN,701.000000,X,NaN,595.000000,X,NaN,538.000000,X,NaN,399.000000,X,NaN,284.000000,X,NaN,350.000000,X,NaN,348.000000,X,NaN,321.000000,X,NaN,300.000000,X,NaN,280.000000,X,NaN,257.000000,X,NaN,233.000000,X,NaN,332.000000,X,NaN,366.000000,X,NaN,361.000000,X,NaN,374.000000,X,NaN,394.000000,X,NaN,471.000000,X,NaN,456.000000,X,NaN,493.000000,X,NaN,505.000000,X,NaN,523.000000,X,NaN,5.540000e+02,X,NaN,5.710000e+02,X,NaN,5.690000e+02,X,NaN,5.440000e+02,X,NaN,5.370000e+02,X,NaN,5.370000e+02,X,NaN,5.310000e+02,X,NaN,5.390000e+02,X,NaN,5.170000e+02,X,NaN

In [6]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15799 entries, 0 to 15798
Columns: 161 entries, Area Code to Y2020N
dtypes: float64(102), int64(3), object(56)
memory usage: 19.4+ MB

In [7]:
#Goal: Simplify the dataframe by deleting Year+F and Year+N
column_headers = list(df_raw.columns.values)
column_headers

['Area Code',
 'Area Code (M49)',
 'Area',
 'Item Code',
 'Item',
 'Element Code',
 'Element',
 'Unit',
 'Y1970',
 'Y1970F',
 'Y1970N',
 'Y1971',
 'Y1971F',
 'Y1971N',
 'Y1972',
 'Y1972F',
 'Y1972N',
 'Y1973',
 'Y1973F',
 'Y1973N',
 'Y1974',
 'Y1974F',
 'Y1974N',
 'Y1975',
 'Y1975F',
 'Y1975N',
 'Y1976',
 'Y1976F',
 'Y1976N',
 'Y1977',
 'Y1977F',
 'Y1977N',
 'Y1978',
 'Y1978F',
 'Y1978N',
 'Y1979',
 'Y1979F',
 'Y1979N',
 'Y1980',
 'Y1980F',
 'Y1980N',
 'Y1981',
 'Y1981F',
 'Y1981N',
 'Y1982',
 'Y1982F',
 'Y1982N',
 'Y1983',
 'Y1983F',
 'Y1983N',
 'Y1984',
 'Y1984F',
 'Y1984N',
 'Y1985',
 'Y1985F',
 'Y1985N',
 'Y1986',
 'Y1986F',
 'Y1986N',
 'Y1987',
 'Y1987F',
 'Y1987N',
 'Y1988',
 'Y1988F',
 'Y1988N',
 'Y1989',
 'Y1989F',
 'Y1989N',
 'Y1990',
 'Y1990F',
 'Y1990N',
 'Y1991',
 'Y1991F',
 'Y1991N',
 'Y1992',
 'Y1992F',
 'Y1992N',
 'Y1993',
 'Y1993F',
 'Y1993N',
 'Y1994',
 'Y1994F',
 'Y1994N',
 'Y1995',
 'Y1995F',
 'Y1995N',
 'Y1996',
 'Y1996F',
 'Y1996N',
 'Y1997',
 'Y1997F',
 'Y1997N',
 'Y1998',
 'Y1998F',
 'Y1998N',
 'Y1999',
 'Y1999F',
 'Y1999N',
 'Y2000',
 'Y2000F',
 'Y2000N',
 'Y2001',
 'Y2001F',
 'Y2001N',
 'Y2002',
 'Y2002F',
 'Y2002N',
 'Y2003',
 'Y2003F',
 'Y2003N',
 'Y2004',
 'Y2004F',
 'Y2004N',
 'Y2005',
 'Y2005F',
 'Y2005N',
 'Y2006',
 'Y2006F',
 'Y2006N',
 'Y2007',
 'Y2007F',
 'Y2007N',
 'Y2008',
 'Y2008F',
 'Y2008N',
 'Y2009',
 'Y2009F',
 'Y2009N',
 'Y2010',
 'Y2010F',
 'Y2010N',
 'Y2011',
 'Y2011F',
 'Y2011N',
 'Y2012',
 'Y2012F',
 'Y2012N',
 'Y2013',
 'Y2013F',
 'Y2013N',
 'Y2014',
 'Y2014F',
 'Y2014N',
 'Y2015',
 'Y2015F',
 'Y2015N',
 'Y2016',
 'Y2016F',
 'Y2016N',
 'Y2017',
 'Y2017F',
 'Y2017N',
 'Y2018',
 'Y2018F',
 'Y2018N',
 'Y2019',
 'Y2019F',
 'Y2019N',
 'Y2020',
 'Y2020F',
 'Y2020N']

In [8]:
for col in df_raw.columns:
    if 'F' in col:
        df_raw.drop(col, axis=1, inplace=True)
    if 'N' in col:
        df_raw.drop(col, axis=1, inplace=True)

In [9]:
df_raw

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020
0,2,'004,Afghanistan,22008,Gross Domestic Product,6109,Value Local Currency,millions,77.911878,81.574837,74.152916,76.619555,92.774575,104.385259,113.107176,128.917758,145.028303,158.776212,160.930107,169.591475,173.589299,172.453817,170.475688,168.520249,168.035667,150.976242,137.322243,161.491528,180.109889,172.172997,174.301038,143.927675,729.118301,2297.365030,6674.524156,8773.855716,8805.572314,100567.527295,158270.632870,170927.404578,195740.846106,230601.118468,257813.610332,307884.813631,354705.069349,470250.593341,514400.361283,583525.091849,682799.599547,811093.070883,9.744573e+05,1.086606e+06,1.119229e+06,1.144181e+06,1.222917e+06,1.285460e+06,1.327690e+06,1.469596e+06,1.520390e+06
1,2,'004,Afghanistan,22008,Gross Domestic Product,6110,Value US$,millions,1731.435587,1812.837521,1647.900178,1702.716294,2061.729287,2319.753506,2513.580659,2864.939207,3222.963833,3630.767856,3646.796868,3427.482014,3430.645143,3408.204613,3369.110951,3330.465681,3320.888887,2983.743471,2713.899488,3191.557068,3559.511736,3402.654940,3444.711414,2844.442641,1715.169169,2756.838036,2669.785634,2924.589326,2935.139404,2157.197316,3342.034168,3598.470576,4141.523943,4729.042179,5388.482107,6220.574147,7104.711445,9412.161765,10236.901594,11595.133469,14698.889678,17350.694945,1.913650e+04,1.962180e+04,1.955070e+04,1.871305e+04,1.801956e+04,1.889635e+04,1.841885e+04,1.890449e+04,1.979326e+04
2,2,'004,Afghanistan,22008,Gross Domestic Product,6119,Value US$ per capita,US$,154.957138,157.975357,139.756605,140.616194,166.095029,182.813796,194.202472,217.513678,241.579792,270.729453,273.035141,260.216148,266.302169,271.835860,276.059517,278.975344,282.961677,257.118767,233.594278,268.901352,286.772753,255.857628,237.803353,179.839036,100.444869,152.221868,141.607370,151.085927,148.706776,106.946309,160.829727,166.541981,183.247028,199.698828,217.921744,242.477079,268.781382,347.305373,369.266275,408.353930,503.636606,576.101770,6.141096e+02,6.080586e+02,5.858627e+02,5.437689e+02,5.092712e+02,5.206164e+02,4.955043e+02,4.969406e+02,5.084537e+02
3,2,'004,Afghanistan,22008,Gross Domestic Product,6183,"Value Local Currency, 2015 prices",millions,640024.694809,638260.085798,556498.281260,545260.592016,571963.541311,606538.115012,640652.358105,622700.035211,650881.544583,647761.511702,625359.636217,630423.153215,643414.185241,670981.813064,687706.446508,691900.378533,708420.513683,656098.152210,598661.464479,554676.102558,532223.150831,483512.600665,476587.229752,385407.968239,296737.925985,387337.309453,401148.285358,380405.169744,362609.298241,345273.395382,326789.905499,308373.050408,458140.931411,530558.854216,545734.797948,586710.864491,636952.631554,781177.101080,772544.956581,856508.039841,901472.494035,962434.513050,1.055821e+06,1.126041e+06,1.160649e+06,1.144181e+06,1.161900e+06,1.192655e+06,1.206839e+06,1.254046e+06,1.229783e+06
4,2,'004,Afghanistan,22008,Gross Domestic Product,6185,"Value US$ per capita, 2015 prices",US$,937.000000,910.000000,772.000000,736.000000,754.000000,782.000000,810.000000,773.000000,798.000000,790.000000,766.000000,783.000000,817.000000,875.000000,922.000000,948.000000,987.000000,925.000000,843.000000,764.000000,701.000000,595.000000,538.000000,399.000000,284.000000,350.000000,348.000000,321.000000,300.000000,280.000000,257.000000,233.000000,332.000000,366.000000,361.000000,374.000000,394.000000,471.000000,456.000000,493.000000,505.000000,523.000000,5.540000e+02,5.710000e+02,5.690000e+02,5.440000e+02,5.370000e+02,5.370000e+02,5.310000e+02,5.390000e+02,5.170000e+02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15794,5817,'902,Net Food Importing Developing Countries,22011,Gross National Income,6103,Share of GDP US$,%,97.416450,97.135921,97.242871,97.341419,98.086288,98.670127,98.476801,98.616841,99.070057,98.919845,99.178230,99.125775,97.714213,97.742129,98.140452,96.883228,97.714363,98.145659,97.541659,97.442350,97.181878,97.305385,95.481618,96.310270,96.263928,97.663603,97.325683,97.874882,98.052489,97.706954,97.537878,97.593593,97.435307,97.738510,97.275909,97.340734,97.678919,98.043392,97.816958,98.356399,98.306356,98.451889,9.856416e+01,9.843464e+01,9.887750e+01,9.923226e+01,9.905498e+01,9.828360e+01,9.781773e+01,9.767972e+01,9.862552e+01
15795,5817,'902,Net Food Importing Developing Countries,22011,Gross National Income,6129,Annual growth US$,%,NaN,7.465709,6.126472,16.943898,26.198685,12.464953,8.058114,12.858459,14.323827,11.196998,17.109434,1.859547,-0.441168,-0.679872,-2.608620,-0.503123,8.319574,4.542378,7.722818,1.366287,5.892764,4.382471,3.858654,-0.085825,4.322462,15.915419,2.901941,6.876795,2.536937,1.691294,4.634836,1.249051,0.173212,6.246079,14.531149,17.015411,17.556465,18.545327,19.015776,2.693287,13.109307,8.093558,8.896547e+00,3.952822e+00,7.392885e+00,-1.168416e+00,-1.675270e+00,2.413034e+00,7.868940e-01,1.621622e+00,4.297660e-01
15796,5817,'902,Net Food Importing Developing Countries,22011,Gross National Income,61290,Annual growth US$ per capita,%,NaN,4.806655,3.408209,14.312631,23.178024,9.689742,5.366832,10.019574,11.456917,8.378599,14.153646,-0.789407,-3.011353,-3.262639,-5.158464,-3.048737,5.597717,1.748552,4.956140,-2.082494,6.990427,1.513612,1.851420,-6.624027,1.719424,13.074847,0.428428,4.353499,0.152829,-0.646282,2.250334,-1.041751,-2.075956,3.881991,12.010819,14.470924,15.032561,16.026650,16.393088,0.814755,10.240427,5.257139,7.274986e+00,1.701644e+00,5.080866e+00,-3.274219e+00,-3.745394e+00,2.799730e-01,-1.293156e+00,-4.618900e-01,-1.618741e+00
15797,5817,'902,Net Food Importing Developing Countries,22011,Gross National Income,6143,Share of Value Added (Total Manufacturing) US$,%,686.881551,676.479644,671.724619,661.442520,632.118942,649.562507,640.269886,655.832235,663.095326,642.740757,655.370005,670.410158,644.101913,633.060985,640.673022,633.102570,617.967989,660.540744,627.406159,656.043681,651.453759,671.216012,662.743428,669.618761,665.253481,660.441251,644.287281,645.936784,666.157888,678.879418,674.554744,682.216642,693.853959,700.480873,685.540319,706.525416,726.247568,733.802550,731.460808,721.209307,736.956601,745.900645,7.450676e+02,7.563768e+02,7.647168e+02,7.575890e+02,7.503457e+02,7.630487e+02,7.494638e+02,7.118064e+02,7.344206e+02
15798,5817,'902,Net Food Importing Developing Countries,22011,Gross National Income,6163,"Ratio of Value Added (Agriculture, Forestry an...",NaN,3.915855,4.053454,4.128555,4.238039,4.411620,4.351000,4.390226,4.482966,4.502286,4.686605,4.979382,5.097277,5.044219,4.967044,4.950164,4.697094,4.594868,4.758592,4.799879,4.682256,4.657795,4.565794,4.696011,4.775383,5.146858,5.335704,5.412539,5.537437,5.633895,5.862806,6.279319,6.435925,6.380209,6.261329,6.565978,6.814907,7.090996,7.141387,7.145942,6.774032,6.975336,6.787165,7.107360e+00,7.139002e+00,7.091600e+00,6.960310e+00,6.759811e+00,6.591877e+00,6.996136e+00,6.992809e+00,6.487359e+00

Annual growth rate of real Gross Domestic Product (GDP) per capita is calculated as the percentage change in the real GDP per capita between two consecutive years. Real GDP per capita is calculated by dividing GDP at constant prices by the population of a country or area. The data for real GDP are measured in constant US dollars to facilitate the calculation of country growth rates and aggregation of the country data.

In [10]:
#Only interested in the GDP with elements: Value US$, 2015 prices(expressed in millions), Value US$ per capita(US$), Annual growth US$ (%), Annual growth US$ per capita(%)

df = df_raw[df_raw['Item'] == 'Gross Domestic Product']
df.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020
0,2,'004,Afghanistan,22008,Gross Domestic Product,6109,Value Local Currency,millions,77.911878,81.574837,74.152916,76.619555,92.774575,104.385259,113.107176,128.917758,145.028303,158.776212,160.930107,169.591475,173.589299,172.453817,170.475688,168.520249,168.035667,150.976242,137.322243,161.491528,180.109889,172.172997,174.301038,143.927675,729.118301,2297.365030,6674.524156,8773.855716,8805.572314,100567.527295,158270.632870,170927.404578,195740.846106,230601.118468,257813.610332,307884.813631,354705.069349,470250.593341,514400.361283,583525.091849,682799.599547,811093.070883,9.744573e+05,1.086606e+06,1.119229e+06,1.144181e+06,1.222917e+06,1.285460e+06,1.327690e+06,1.469596e+06,1.520390e+06
1,2,'004,Afghanistan,22008,Gross Domestic Product,6110,Value US$,millions,1731.435587,1812.837521,1647.900178,1702.716294,2061.729287,2319.753506,2513.580659,2864.939207,3222.963833,3630.767856,3646.796868,3427.482014,3430.645143,3408.204613,3369.110951,3330.465681,3320.888887,2983.743471,2713.899488,3191.557068,3559.511736,3402.654940,3444.711414,2844.442641,1715.169169,2756.838036,2669.785634,2924.589326,2935.139404,2157.197316,3342.034168,3598.470576,4141.523943,4729.042179,5388.482107,6220.574147,7104.711445,9412.161765,10236.901594,11595.133469,14698.889678,17350.694945,1.913650e+04,1.962180e+04,1.955070e+04,1.871305e+04,1.801956e+04,1.889635e+04,1.841885e+04,1.890449e+04,1.979326e+04
2,2,'004,Afghanistan,22008,Gross Domestic Product,6119,Value US$ per capita,US$,154.957138,157.975357,139.756605,140.616194,166.095029,182.813796,194.202472,217.513678,241.579792,270.729453,273.035141,260.216148,266.302169,271.835860,276.059517,278.975344,282.961677,257.118767,233.594278,268.901352,286.772753,255.857628,237.803353,179.839036,100.444869,152.221868,141.607370,151.085927,148.706776,106.946309,160.829727,166.541981,183.247028,199.698828,217.921744,242.477079,268.781382,347.305373,369.266275,408.353930,503.636606,576.101770,6.141096e+02,6.080586e+02,5.858627e+02,5.437689e+02,5.092712e+02,5.206164e+02,4.955043e+02,4.969406e+02,5.084537e+02
3,2,'004,Afghanistan,22008,Gross Domestic Product,6183,"Value Local Currency, 2015 prices",millions,640024.694809,638260.085798,556498.281260,545260.592016,571963.541311,606538.115012,640652.358105,622700.035211,650881.544583,647761.511702,625359.636217,630423.153215,643414.185241,670981.813064,687706.446508,691900.378533,708420.513683,656098.152210,598661.464479,554676.102558,532223.150831,483512.600665,476587.229752,385407.968239,296737.925985,387337.309453,401148.285358,380405.169744,362609.298241,345273.395382,326789.905499,308373.050408,458140.931411,530558.854216,545734.797948,586710.864491,636952.631554,781177.101080,772544.956581,856508.039841,901472.494035,962434.513050,1.055821e+06,1.126041e+06,1.160649e+06,1.144181e+06,1.161900e+06,1.192655e+06,1.206839e+06,1.254046e+06,1.229783e+06
4,2,'004,Afghanistan,22008,Gross Domestic Product,6185,"Value US$ per capita, 2015 prices",US$,937.000000,910.000000,772.000000,736.000000,754.000000,782.000000,810.000000,773.000000,798.000000,790.000000,766.000000,783.000000,817.000000,875.000000,922.000000,948.000000,987.000000,925.000000,843.000000,764.000000,701.000000,595.000000,538.000000,399.000000,284.000000,350.000000,348.000000,321.000000,300.000000,280.000000,257.000000,233.000000,332.000000,366.000000,361.000000,374.000000,394.000000,471.000000,456.000000,493.000000,505.000000,523.000000,5.540000e+02,5.710000e+02,5.690000e+02,5.440000e+02,5.370000e+02,5.370000e+02,5.310000e+02,5.390000e+02,5.170000e+02

In [11]:
df = df[df['Element'].isin(['Value US$', 'Value US$ per capita', 'Annual growth US$, 2015 prices', 'Annual growth US$ per capita, 2015 prices'])]

In [12]:
df.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1970,Y1971,Y1972,Y1973,Y1974,Y1975,Y1976,Y1977,Y1978,Y1979,Y1980,Y1981,Y1982,Y1983,Y1984,Y1985,Y1986,Y1987,Y1988,Y1989,Y1990,Y1991,Y1992,Y1993,Y1994,Y1995,Y1996,Y1997,Y1998,Y1999,Y2000,Y2001,Y2002,Y2003,Y2004,Y2005,Y2006,Y2007,Y2008,Y2009,Y2010,Y2011,Y2012,Y2013,Y2014,Y2015,Y2016,Y2017,Y2018,Y2019,Y2020
1,2,'004,Afghanistan,22008,Gross Domestic Product,6110,Value US$,millions,1731.435587,1812.837521,1647.900178,1702.716294,2061.729287,2319.753506,2513.580659,2864.939207,3222.963833,3630.767856,3646.796868,3427.482014,3430.645143,3408.204613,3369.110951,3330.465681,3320.888887,2983.743471,2713.899488,3191.557068,3559.511736,3402.654940,3444.711414,2844.442641,1715.169169,2756.838036,2669.785634,2924.589326,2935.139404,2157.197316,3342.034168,3598.470576,4141.523943,4729.042179,5388.482107,6220.574147,7104.711445,9412.161765,10236.901594,11595.133469,14698.889678,17350.694945,19136.499341,19621.802455,19550.702567,18713.048410,18019.558182,18896.352021,18418.848300,18904.490263,19793.262413
2,2,'004,Afghanistan,22008,Gross Domestic Product,6119,Value US$ per capita,US$,154.957138,157.975357,139.756605,140.616194,166.095029,182.813796,194.202472,217.513678,241.579792,270.729453,273.035141,260.216148,266.302169,271.835860,276.059517,278.975344,282.961677,257.118767,233.594278,268.901352,286.772753,255.857628,237.803353,179.839036,100.444869,152.221868,141.607370,151.085927,148.706776,106.946309,160.829727,166.541981,183.247028,199.698828,217.921744,242.477079,268.781382,347.305373,369.266275,408.353930,503.636606,576.101770,614.109574,608.058642,585.862673,543.768940,509.271172,520.616409,495.504343,496.940553,508.453722
10,2,'004,Afghanistan,22008,Gross Domestic Product,6182,"Annual growth US$, 2015 prices",%,NaN,-0.275710,-12.810108,-2.019357,4.897282,6.044891,5.624419,-2.802194,4.525696,-0.479355,-3.458352,0.809697,2.060684,4.284585,2.492561,0.609843,2.387646,-7.385777,-8.754283,-7.347285,-4.047939,-9.152279,-1.432304,-19.131705,-23.006800,30.531784,3.565620,-5.170935,-4.678136,-4.780877,-5.353291,-5.635687,48.567111,15.806910,2.860370,7.508421,8.563292,22.642888,-1.105018,10.868375,5.249741,6.762494,9.703175,6.650733,3.073402,-1.418885,1.548655,2.647003,1.189228,3.911603,-1.934778
11,2,'004,Afghanistan,22008,Gross Domestic Product,61820,"Annual growth US$ per capita, 2015 prices",%,NaN,-2.881537,-15.164835,-4.663212,2.445652,3.713528,3.580563,-4.567901,3.234153,-1.002506,-3.037975,2.219321,4.342273,7.099143,5.371429,2.819957,4.113924,-6.281662,-8.864865,-9.371293,-8.246073,-15.121255,-9.579832,-25.836431,-28.822055,23.239437,-0.571429,-7.758621,-6.542056,-6.666667,-8.214286,-9.338521,42.489270,10.240964,-1.366120,3.601108,5.347594,19.543147,-3.184713,8.114035,2.434077,3.564356,5.927342,3.068592,-0.350263,-4.393673,-1.286765,0.000000,-1.117318,1.506591,-4.081633
57,3,'008,Albania,22008,Gross Domestic Product,6110,Value US$,millions,2265.577056,2330.584860,2397.526448,2466.543461,2537.015817,2610.110369,2685.745678,2760.746397,2842.275926,2372.305641,2141.837051,2215.474766,2280.424885,2305.384485,2275.736342,2324.414456,2397.086883,2378.194810,2460.399974,2940.586487,2145.751209,1597.139589,1516.132824,1700.439125,1880.950821,2392.764887,3199.642024,2224.654241,2554.868837,3221.670165,3487.586302,3926.887597,4355.865889,5561.459461,7177.030365,8052.079314,8896.076004,10677.322220,12881.352058,12044.210390,11926.948284,12890.873323,12319.779604,12776.280738,13228.240079,11386.924853,11861.356451,13019.729856,15156.439968,15400.237155,14909.619335

In [13]:
#Save the transformed dataset

In [14]:
df.to_csv('../data/gdp_clean.csv')

In [15]:
df['Area'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Anguilla', 'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba',
       'Australia', 'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin',
       'Bermuda', 'Bhutan', 'Bolivia (Plurinational State of)',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei Darussalam', 'Bulgaria',
       'Burkina Faso', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon',
       'Canada', 'Cayman Islands', 'Central African Republic', 'Chad',
       'Chile', 'China', 'China, Hong Kong SAR', 'China, Macao SAR',
       'China, mainland', 'Colombia', 'Comoros', 'Congo', 'Cook Islands',
       'Costa Rica', "Côte d'Ivoire", 'Croatia', 'Cuba', 'Curaçao',
       'Cyprus', 'Czechia', 'Czechoslovakia',
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Ethiopia PDR', 'Fiji', 'Finland',
       'France', 'French Polynesia', 'Gabon', 'Gambia', 'Georgia',
       'Germany', 'Ghana', 'Greece', 'Greenland', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras',
       'Hungary', 'Iceland', 'India', 'Indonesia',
       'Iran (Islamic Republic of)', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kuwait', 'Kyrgyzstan', "Lao People's Democratic Republic",
       'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya',
       'Liechtenstein', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi',
       'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands',
       'Mauritania', 'Mauritius', 'Mexico',
       'Micronesia (Federated States of)', 'Monaco', 'Mongolia',
       'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
       'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'Netherlands Antilles (former)', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'North Macedonia', 'Norway',
       'Oman', 'Pakistan', 'Palau', 'Palestine', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland',
       'Portugal', 'Puerto Rico', 'Qatar', 'Republic of Korea',
       'Republic of Moldova', 'Romania', 'Russian Federation', 'Rwanda',
       'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore',
       'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Sudan',
       'Spain', 'Sri Lanka', 'Sudan', 'Sudan (former)', 'Suriname',
       'Sweden', 'Switzerland', 'Syrian Arab Republic', 'Tajikistan',
       'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Trinidad and Tobago',
       'Tunisia', 'Türkiye', 'Turkmenistan', 'Turks and Caicos Islands',
       'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
       'United Kingdom of Great Britain and Northern Ireland',
       'United Republic of Tanzania', 'United States of America',
       'Uruguay', 'USSR', 'Uzbekistan', 'Vanuatu',
       'Venezuela (Bolivarian Republic of)', 'Viet Nam', 'Yemen',
       'Yemen Ar Rp', 'Yemen Dem', 'Yugoslav SFR', 'Zambia', 'Zimbabwe',
       'World', 'Africa', 'Eastern Africa', 'Middle Africa',
       'Northern Africa', 'Southern Africa', 'Western Africa', 'Americas',
       'Northern America', 'Central America', 'Caribbean',
       'South America', 'Asia', 'Central Asia', 'Eastern Asia',
       'Southern Asia', 'South-eastern Asia', 'Western Asia', 'Europe',
       'Eastern Europe', 'Northern Europe', 'Southern Europe',
       'Western Europe', 'Oceania', 'Australia and New Zealand',
       'Melanesia', 'Micronesia', 'Polynesia', 'European Union (27)',
       'Least Developed Countries', 'Land Locked Developing Countries',
       'Small Island Developing States',
       'Low Income Food Deficit Countries',
       'Net Food Importing Developing Countries'], dtype=object)

## Emissions dataset ##

In [19]:
em_raw = pd.read_csv('../data/FAOSTAT_Emissions_E_All.csv')

In [20]:
em_raw.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Source Code,Source,Unit,Y1961,Y1961F,Y1961N,Y1962,Y1962F,Y1962N,Y1963,Y1963F,Y1963N,Y1964,Y1964F,Y1964N,Y1965,Y1965F,Y1965N,Y1966,Y1966F,Y1966N,Y1967,Y1967F,Y1967N,Y1968,Y1968F,Y1968N,Y1969,Y1969F,Y1969N,Y1970,Y1970F,Y1970N,Y1971,Y1971F,Y1971N,Y1972,Y1972F,Y1972N,Y1973,Y1973F,Y1973N,Y1974,Y1974F,Y1974N,Y1975,Y1975F,Y1975N,Y1976,Y1976F,Y1976N,Y1977,Y1977F,Y1977N,Y1978,Y1978F,Y1978N,Y1979,Y1979F,Y1979N,Y1980,Y1980F,Y1980N,Y1981,Y1981F,Y1981N,Y1982,Y1982F,Y1982N,Y1983,Y1983F,Y1983N,Y1984,Y1984F,Y1984N,Y1985,Y1985F,Y1985N,Y1986,Y1986F,Y1986N,Y1987,Y1987F,Y1987N,Y1988,Y1988F,Y1988N,Y1989,Y1989F,Y1989N,Y1990,Y1990F,Y1990N,Y1991,Y1991F,Y1991N,Y1992,Y1992F,Y1992N,Y1993,Y1993F,Y1993N,Y1994,Y1994F,Y1994N,Y1995,Y1995F,Y1995N,Y1996,Y1996F,Y1996N,Y1997,Y1997F,Y1997N,Y1998,Y1998F,Y1998N,Y1999,Y1999F,Y1999N,Y2000,Y2000F,Y2000N,Y2001,Y2001F,Y2001N,Y2002,Y2002F,Y2002N,Y2003,Y2003F,Y2003N,Y2004,Y2004F,Y2004N,Y2005,Y2005F,Y2005N,Y2006,Y2006F,Y2006N,Y2007,Y2007F,Y2007N,Y2008,Y2008F,Y2008N,Y2009,Y2009F,Y2009N,Y2010,Y2010F,Y2010N,Y2011,Y2011F,Y2011N,Y2012,Y2012F,Y2012N,Y2013,Y2013F,Y2013N,Y2014,Y2014F,Y2014N,Y2015,Y2015F,Y2015N,Y2016,Y2016F,Y2016N,Y2017,Y2017F,Y2017N,Y2018,Y2018F,Y2018N,Y2019,Y2019F,Y2019N,Y2020,Y2020F,Y2020N,Y2021,Y2021F,Y2021N,Y2030,Y2030F,Y2030N,Y2050,Y2050F,Y2050N
0,2,'004,Afghanistan,5064,Crop Residues,7234,Direct emissions (N2O),3050,FAO TIER 1,kilotonnes,0.8762,E,NaN,0.8829,E,NaN,0.8236,E,NaN,0.8882,E,NaN,0.8978,E,NaN,0.8466,E,NaN,0.8783,E,NaN,0.8886,E,NaN,0.9123,E,NaN,0.8304,E,NaN,0.8093,E,NaN,0.9531,E,NaN,0.9725,E,NaN,0.9880,E,NaN,1.0138,E,NaN,1.0401,E,NaN,0.9566,E,NaN,0.9972,E,NaN,0.9533,E,NaN,0.9156,E,NaN,0.8766,E,NaN,0.8407,E,NaN,0.8065,E,NaN,0.7713,E,NaN,0.7319,E,NaN,0.6981,E,NaN,0.7706,E,NaN,0.6917,E,NaN,0.6601,E,NaN,0.6334,E,NaN,0.6454,E,NaN,0.6054,E,NaN,0.7110,E,NaN,0.7456,E,NaN,0.7511,E,NaN,0.7672,E,NaN,0.8511,E,NaN,0.8854,E,NaN,0.7624,E,NaN,0.520,E,NaN,0.5267,E,NaN,0.8200,E,NaN,0.9988,E,NaN,0.8225,E,NaN,1.1821,E,NaN,1.0277,E,NaN,1.2426,E,NaN,0.8869,E,NaN,1.3920,E,NaN,1.2742,E,NaN,1.0321,E,NaN,1.3726,E,NaN,1.4018,E,NaN,1.4584,E,NaN,1.2424,E,NaN,1.1940,E,NaN,1.0617,E,NaN,0.8988,E,NaN,1.2176,E,NaN,1.3170,E,NaN,NaN,NaN,NaN,1.5337,E,NaN,1.9389,E,NaN
1,2,'004,Afghanistan,5064,Crop Residues,7236,Indirect emissions (N2O),3050,FAO TIER 1,kilotonnes,0.1972,E,NaN,0.1987,E,NaN,0.1853,E,NaN,0.1998,E,NaN,0.2020,E,NaN,0.1905,E,NaN,0.1976,E,NaN,0.1999,E,NaN,0.2053,E,NaN,0.1868,E,NaN,0.1821,E,NaN,0.2145,E,NaN,0.2188,E,NaN,0.2223,E,NaN,0.2281,E,NaN,0.2340,E,NaN,0.2152,E,NaN,0.2244,E,NaN,0.2145,E,NaN,0.2060,E,NaN,0.1972,E,NaN,0.1892,E,NaN,0.1815,E,NaN,0.1735,E,NaN,0.1647,E,NaN,0.1571,E,NaN,0.1734,E,NaN,0.1556,E,NaN,0.1485,E,NaN,0.1425,E,NaN,0.1452,E,NaN,0.1362,E,NaN,0.1600,E,NaN,0.1678,E,NaN,0.1690,E,NaN,0.1726,E,NaN,0.1915,E,NaN,0.1992,E,NaN,0.1715,E,NaN,0.117,E,NaN,0.1185,E,NaN,0.1845,E,NaN,0.2247,E,NaN,0.1851,E,NaN,0.2660,E,NaN,0.2312,E,NaN,0.2796,E,NaN,0.1996,E,NaN,0.3132,E,NaN,0.2867,E,NaN,0.2322,E,NaN,0.3088,E,NaN,0.3154,E,NaN,0.3281,E,NaN,0.2795,E,NaN,0.2687,E,NaN,0.2389,E,NaN,0.2022,E,NaN,0.2740,E,NaN,0.2963,E,NaN,NaN,NaN,NaN,0.3451,E,NaN,0.4362,E,NaN
2,2,'004,Afghanistan,5064,Crop Residues,7230,Emissions (N2O),3050,FAO TIER 1,kilotonnes,1.0734,E,NaN,1.0816,E,NaN,1.0089,E,NaN,1.0880,E,NaN,1.0998,E,NaN,1.0371,E,NaN,1.0759,E,NaN,1.0885,E,NaN,1.1176,E,NaN,1.0172,E,NaN,0.9914,E,NaN,1.1676,E,NaN,1.1913,E,NaN,1.2103,E,NaN,1.2419,E,NaN,1.2741,E,NaN,1.1718,E,NaN,1.2215,E,NaN,1.1678,E,NaN,1.1216,E,NaN,1.0738,E,NaN,1.0299,E,NaN,0.9880,E,NaN,0.9448,E,NaN,0.8965,E,NaN,0.8551,E,NaN,0.9439,E,NaN,0.8473,E,NaN,0.8086,E,NaN,0.7759,E,NaN,0.7906,E,NaN,0.7416,E,NaN,0.8710,E,NaN,0.9134,E,NaN,0.9201,E,NaN,0.9398,E,NaN,1.0426,E,NaN,1.0847,E,NaN,0.9340,E,NaN,0.637,E,NaN,0.6452,E,NaN,1.0045,E,NaN,1.2235,E,NaN,1.0075,E,NaN,1.4481,E,NaN,1.2589,E,NaN,1.5222,E,NaN,1.0865,E,NaN,1.7051,E,NaN,1.5609,E,NaN,1.2643,E,NaN,1.6815,E,NaN,1.7173,E,NaN,1.7865,E,NaN,1.5220,E,NaN,1.4627,E,NaN,1.3005,E,NaN,1.1011,E,NaN,1.4916,E,NaN,1.6133,E,NaN,NaN,NaN,NaN,1.8788,E,NaN,2.3751,E,NaN
3,2,'004,Afghanistan,5064,Crop Residues,724313,Emissions (CO2eq) from N2O (AR5),3050,FAO TIER 1,kilotonnes,284.4486,E,NaN,286.6192,E,NaN,267.3466,E,NaN,288.3212,E,NaN,291.4406,E,NaN,274.8304,E,NaN,285.1026,E,NaN,288.4483,E,NaN,296.1556,E,NaN,269.5529,E,NaN,262.7338,E,NaN,309.4116,E,NaN,315.6948,E,NaN,320.7274,E,NaN,329.1046,E,NaN,337.6487,E,NaN,310.5341,E,NaN,323.7090,E,NaN,309.4714,E,NaN,297.2257,E,NaN,284.5502,E,NaN,272.9278,E,NaN,261.8147,E,NaN,250.3726,E,NaN,237.5808,E,NaN,226.6047,E,NaN,250.1406,E,NaN,224.5390,E,NaN,214.2788,E,NaN,205.6077,E,NaN,209.4971,E,NaN,196.5341,E,NaN,230.8175,E,NaN,242.0494,E,NaN,243.8152,E,NaN,249.0364,E,NaN,276.2940,E,NaN,287.4346,E,NaN,247.4980,E,NaN,168.807,E,NaN,170.9884,E,NaN,266.1975,E,NaN,324.2195,E,NaN,266.9995,E,NaN,383.7498,E,NaN,333.6093,E,NaN,403.3749,E,NaN,287.9099,E,NaN,451.8647,E,NaN,413.6467,E,NaN,335.0379,E,NaN,445.5958,E,NaN,455.0727,E,NaN,473.4174,E,NaN,403.3181,E,NaN,387.6130,E,NaN,344.6447,E,NaN,291.7838,E,NaN,395.2689,E,NaN,427.5284,E,NaN,NaN,NaN,NaN,497.8929,E,NaN,629.4047,E,NaN
4,2,'004,Afghanistan,5064,Crop Residues,723113,Emissions (CO2eq) (AR5),3050,FAO TIER 1,kilotonnes,284.4486,E,NaN,286.6192,E,NaN,267.3466,E,NaN,288.3212,E,NaN,291.4406,E,NaN,274.8304,E,NaN,285.1026,E,NaN,288.4483,E,NaN,296.1556,E,NaN,269.5529,E,NaN,262.7338,E,NaN,309.4116,E,NaN,315.6948,E,NaN,320.7274,E,NaN,329.1046,E,NaN,337.6487,E,NaN,310.5341,E,NaN,323.7090,E,NaN,309.4714,E,NaN,297.2257,E,NaN,284.5502,E,NaN,272.9278,E,NaN,261.8147,E,NaN,250.3726,E,NaN,237.5808,E,NaN,226.6047,E,NaN,250.1406,E,NaN,224.5390,E,NaN,214.2788,E,NaN,205.6077,E,NaN,209.4971,E,NaN,196.5341,E,NaN,230.8175,E,NaN,242.0494,E,NaN,243.8152,E,NaN,249.0364,E,NaN,276.2940,E,NaN,287.4346,E,NaN,247.4980,E,NaN,168.807,E,NaN,170.9884,E,NaN,266.1975,E,NaN,324.2195,E,NaN,266.9995,E,NaN,383.7498,E,NaN,333.6093,E,NaN,403.3749,E,NaN,287.9099,E,NaN,451.8647,E,NaN,413.6467,E,NaN,335.0379,E,NaN,445.5958,E,NaN,455.0727,E,NaN,473.4174,E,NaN,403.3181,E,NaN,387.6130,E,NaN,344.6447,E,NaN,291.7838,E,NaN,395.2689,E,NaN,427.5284,E,NaN,NaN,NaN,NaN,497.8929,E,NaN,629.4047,E,NaN

In [ ]:
for col in df_raw.columns:
    if 'F' in col:
        df_raw.drop(col, axis=1, inplace=True)
    if 'N' in col:
        df_raw.drop(col, axis=1, inplace=True)