In [17]:
import pandas as pd
pd.set_option('display.max_columns', None)

ModuleNotFoundError: No module named 'chardet'

In [12]:
df = pd.read_csv('../data/FAOSTAT_temperature.csv')

In [13]:
df.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Months Code,Months,Year Code,Year,Unit,Value,Flag,Flag Description
0,ET,Temperature change,4,Afghanistan,7271,Temperature change,7020,Meteorological year,1961,1961,°C,-0.105,E,Estimated value
1,ET,Temperature change,4,Afghanistan,7271,Temperature change,7020,Meteorological year,1962,1962,°C,-0.157,E,Estimated value
2,ET,Temperature change,4,Afghanistan,7271,Temperature change,7020,Meteorological year,1963,1963,°C,0.852,E,Estimated value
3,ET,Temperature change,4,Afghanistan,7271,Temperature change,7020,Meteorological year,1964,1964,°C,-0.743,E,Estimated value
4,ET,Temperature change,4,Afghanistan,7271,Temperature change,7020,Meteorological year,1965,1965,°C,-0.211,E,Estimated value

In [21]:
df1 = pd.read_csv('../data/FAOSTAT_economic_growth.csv', encoding = 'latin')

In [22]:
df1.head()

,Area Code,Area Code (M49),Area,Item Code,Item,Element Code,Element,Unit,Y1970,Y1970F,Y1970N,Y1971,Y1971F,Y1971N,Y1972,Y1972F,Y1972N,Y1973,Y1973F,Y1973N,Y1974,Y1974F,Y1974N,Y1975,Y1975F,Y1975N,Y1976,Y1976F,Y1976N,Y1977,Y1977F,Y1977N,Y1978,Y1978F,Y1978N,Y1979,Y1979F,Y1979N,Y1980,Y1980F,Y1980N,Y1981,Y1981F,Y1981N,Y1982,Y1982F,Y1982N,Y1983,Y1983F,Y1983N,Y1984,Y1984F,Y1984N,Y1985,Y1985F,Y1985N,Y1986,Y1986F,Y1986N,Y1987,Y1987F,Y1987N,Y1988,Y1988F,Y1988N,Y1989,Y1989F,Y1989N,Y1990,Y1990F,Y1990N,Y1991,Y1991F,Y1991N,Y1992,Y1992F,Y1992N,Y1993,Y1993F,Y1993N,Y1994,Y1994F,Y1994N,Y1995,Y1995F,Y1995N,Y1996,Y1996F,Y1996N,Y1997,Y1997F,Y1997N,Y1998,Y1998F,Y1998N,Y1999,Y1999F,Y1999N,Y2000,Y2000F,Y2000N,Y2001,Y2001F,Y2001N,Y2002,Y2002F,Y2002N,Y2003,Y2003F,Y2003N,Y2004,Y2004F,Y2004N,Y2005,Y2005F,Y2005N,Y2006,Y2006F,Y2006N,Y2007,Y2007F,Y2007N,Y2008,Y2008F,Y2008N,Y2009,Y2009F,Y2009N,Y2010,Y2010F,Y2010N,Y2011,Y2011F,Y2011N,Y2012,Y2012F,Y2012N,Y2013,Y2013F,Y2013N,Y2014,Y2014F,Y2014N,Y2015,Y2015F,Y2015N,Y2016,Y2016F,Y2016N,Y2017,Y2017F,Y2017N,Y2018,Y2018F,Y2018N,Y2019,Y2019F,Y2019N,Y2020,Y2020F,Y2020N
0,2,'004,Afghanistan,22008,Gross Domestic Product,6109,Value Local Currency,millions,77.911878,X,NaN,81.574837,X,NaN,74.152916,X,NaN,76.619555,X,NaN,92.774575,X,NaN,104.385259,X,NaN,113.107176,X,NaN,128.917758,X,NaN,145.028303,X,NaN,158.776212,X,NaN,160.930107,X,NaN,169.591475,X,NaN,173.589299,X,NaN,172.453817,X,NaN,170.475688,X,NaN,168.520249,X,NaN,168.035667,X,NaN,150.976242,X,NaN,137.322243,X,NaN,161.491528,X,NaN,180.109889,X,NaN,172.172997,X,NaN,174.301038,X,NaN,143.927675,X,NaN,729.118301,X,NaN,2297.365030,X,NaN,6674.524156,X,NaN,8773.855716,X,NaN,8805.572314,X,NaN,100567.527295,X,NaN,158270.632870,X,NaN,170927.404578,X,NaN,195740.846106,X,NaN,230601.118468,X,NaN,257813.610332,X,NaN,307884.813631,X,NaN,354705.069349,X,NaN,470250.593341,X,NaN,514400.361283,X,NaN,583525.091849,X,NaN,682799.599547,X,NaN,811093.070883,X,NaN,9.744573e+05,X,NaN,1.086606e+06,X,NaN,1.119229e+06,X,NaN,1.144181e+06,X,NaN,1.222917e+06,X,NaN,1.285460e+06,X,NaN,1.327690e+06,X,NaN,1.469596e+06,X,NaN,1.520390e+06,X,NaN
1,2,'004,Afghanistan,22008,Gross Domestic Product,6110,Value US$,millions,1731.435587,X,NaN,1812.837521,X,NaN,1647.900178,X,NaN,1702.716294,X,NaN,2061.729287,X,NaN,2319.753506,X,NaN,2513.580659,X,NaN,2864.939207,X,NaN,3222.963833,X,NaN,3630.767856,X,NaN,3646.796868,X,NaN,3427.482014,X,NaN,3430.645143,X,NaN,3408.204613,X,NaN,3369.110951,X,NaN,3330.465681,X,NaN,3320.888887,X,NaN,2983.743471,X,NaN,2713.899488,X,NaN,3191.557068,X,NaN,3559.511736,X,NaN,3402.654940,X,NaN,3444.711414,X,NaN,2844.442641,X,NaN,1715.169169,X,NaN,2756.838036,X,NaN,2669.785634,X,NaN,2924.589326,X,NaN,2935.139404,X,NaN,2157.197316,X,NaN,3342.034168,X,NaN,3598.470576,X,NaN,4141.523943,X,NaN,4729.042179,X,NaN,5388.482107,X,NaN,6220.574147,X,NaN,7104.711445,X,NaN,9412.161765,X,NaN,10236.901594,X,NaN,11595.133469,X,NaN,14698.889678,X,NaN,17350.694945,X,NaN,1.913650e+04,X,NaN,1.962180e+04,X,NaN,1.955070e+04,X,NaN,1.871305e+04,X,NaN,1.801956e+04,X,NaN,1.889635e+04,X,NaN,1.841885e+04,X,NaN,1.890449e+04,X,NaN,1.979326e+04,X,NaN
2,2,'004,Afghanistan,22008,Gross Domestic Product,6119,Value US$ per capita,US$,154.957138,X,NaN,157.975357,X,NaN,139.756605,X,NaN,140.616194,X,NaN,166.095029,X,NaN,182.813796,X,NaN,194.202472,X,NaN,217.513678,X,NaN,241.579792,X,NaN,270.729453,X,NaN,273.035141,X,NaN,260.216148,X,NaN,266.302169,X,NaN,271.835860,X,NaN,276.059517,X,NaN,278.975344,X,NaN,282.961677,X,NaN,257.118767,X,NaN,233.594278,X,NaN,268.901352,X,NaN,286.772753,X,NaN,255.857628,X,NaN,237.803353,X,NaN,179.839036,X,NaN,100.444869,X,NaN,152.221868,X,NaN,141.607370,X,NaN,151.085927,X,NaN,148.706776,X,NaN,106.946309,X,NaN,160.829727,X,NaN,166.541981,X,NaN,183.247028,X,NaN,199.698828,X,NaN,217.921744,X,NaN,242.477079,X,NaN,268.781382,X,NaN,347.305373,X,NaN,369.266275,X,NaN,408.353930,X,NaN,503.636606,X,NaN,576.101770,X,NaN,6.141096e+02,X,NaN,6.080586e+02,X,NaN,5.858627e+02,X,NaN,5.437689e+02,X,NaN,5.092712e+02,X,NaN,5.206164e+02,X,NaN,4.955043e+02,X,NaN,4.969406e+02,X,NaN,5.084537e+02,X,NaN
3,2,'004,Afghanistan,22008,Gross Domestic Product,6183,"Value Local Currency, 2015 prices",millions,640024.694809,X,NaN,638260.085798,X,NaN,556498.281260,X,NaN,545260.592016,X,NaN,571963.541311,X,NaN,606538.115012,X,NaN,640652.358105,X,NaN,622700.035211,X,NaN,650881.544583,X,NaN,647761.511702,X,NaN,625359.636217,X,NaN,630423.153215,X,NaN,643414.185241,X,NaN,670981.813064,X,NaN,687706.446508,X,NaN,691900.378533,X,NaN,708420.513683,X,NaN,656098.152210,X,NaN,598661.464479,X,NaN,554676.102558,X,NaN,532223.150831,X,NaN,483512.600665,X,NaN,476587.229752,X,NaN,385407.968239,X,NaN,296737.925985,X,NaN,387337.309453,X,NaN,401148.285358,X,NaN,380405.169744,X,NaN,362609.298241,X,NaN,345273.395382,X,NaN,326789.905499,X,NaN,308373.050408,X,NaN,458140.931411,X,NaN,530558.854216,X,NaN,545734.797948,X,NaN,586710.864491,X,NaN,636952.631554,X,NaN,781177.101080,X,NaN,772544.956581,X,NaN,856508.039841,X,NaN,901472.494035,X,NaN,962434.513050,X,NaN,1.055821e+06,X,NaN,1.126041e+06,X,NaN,1.160649e+06,X,NaN,1.144181e+06,X,NaN,1.161900e+06,X,NaN,1.192655e+06,X,NaN,1.206839e+06,X,NaN,1.254046e+06,X,NaN,1.229783e+06,X,NaN
4,2,'004,Afghanistan,22008,Gross Domestic Product,6185,"Value US$ per capita, 2015 prices",US$,937.000000,X,NaN,910.000000,X,NaN,772.000000,X,NaN,736.000000,X,NaN,754.000000,X,NaN,782.000000,X,NaN,810.000000,X,NaN,773.000000,X,NaN,798.000000,X,NaN,790.000000,X,NaN,766.000000,X,NaN,783.000000,X,NaN,817.000000,X,NaN,875.000000,X,NaN,922.000000,X,NaN,948.000000,X,NaN,987.000000,X,NaN,925.000000,X,NaN,843.000000,X,NaN,764.000000,X,NaN,701.000000,X,NaN,595.000000,X,NaN,538.000000,X,NaN,399.000000,X,NaN,284.000000,X,NaN,350.000000,X,NaN,348.000000,X,NaN,321.000000,X,NaN,300.000000,X,NaN,280.000000,X,NaN,257.000000,X,NaN,233.000000,X,NaN,332.000000,X,NaN,366.000000,X,NaN,361.000000,X,NaN,374.000000,X,NaN,394.000000,X,NaN,471.000000,X,NaN,456.000000,X,NaN,493.000000,X,NaN,505.000000,X,NaN,523.000000,X,NaN,5.540000e+02,X,NaN,5.710000e+02,X,NaN,5.690000e+02,X,NaN,5.440000e+02,X,NaN,5.370000e+02,X,NaN,5.370000e+02,X,NaN,5.310000e+02,X,NaN,5.390000e+02,X,NaN,5.170000e+02,X,NaN

In [26]:
df2 = pd.read_csv('../data/FAOSTAT_emissions.csv', encoding ='latin')

C:\Users\raque\AppData\Local\Temp\ipykernel_9836\3693192581.py:1: DtypeWarning: Columns (99,102,105,108,111,114,117,120,123,126,129,132,135,138,141,144,147,150,153,156,159,162,165,168,171,174,177,180,183,186,189,191) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv('../data/FAOSTAT_emissions.csv', encoding ='latin')

In [29]:
df2.info(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58765 entries, 0 to 58764
Data columns (total 199 columns):
 #    Column           Dtype
---   ------           -----
 0    Area Code        int64
 1    Area Code (M49)  object
 2    Area             object
 3    Item Code        int64
 4    Item             object
 5    Element Code     int64
 6    Element          object
 7    Source Code      int64
 8    Source           object
 9    Unit             object
 10   Y1961            float64
 11   Y1961F           object
 12   Y1961N           float64
 13   Y1962            float64
 14   Y1962F           object
 15   Y1962N           float64
 16   Y1963            float64
 17   Y1963F           object
 18   Y1963N           float64
 19   Y1964            float64
 20   Y1964F           object
 21   Y1964N           float64
 22   Y1965            float64
 23   Y1965F           object
 24   Y1965N           float64
 25   Y1966            float64
 26   Y1966F           object
 27   Y1966N           float64
 28   Y1967            float64
 29   Y1967F           object
 30   Y1967N           float64
 31   Y1968            float64
 32   Y1968F           object
 33   Y1968N           float64
 34   Y1969            float64
 35   Y1969F           object
 36   Y1969N           float64
 37   Y1970            float64
 38   Y1970F           object
 39   Y1970N           float64
 40   Y1971            float64
 41   Y1971F           object
 42   Y1971N           float64
 43   Y1972            float64
 44   Y1972F           object
 45   Y1972N           float64
 46   Y1973            float64
 47   Y1973F           object
 48   Y1973N           float64
 49   Y1974            float64
 50   Y1974F           object
 51   Y1974N           float64
 52   Y1975            float64
 53   Y1975F           object
 54   Y1975N           float64
 55   Y1976            float64
 56   Y1976F           object
 57   Y1976N           float64
 58   Y1977            float64
 59   Y1977F           object
 60   Y1977N           float64
 61   Y1978            float64
 62   Y1978F           object
 63   Y1978N           float64
 64   Y1979            float64
 65   Y1979F           object
 66   Y1979N           float64
 67   Y1980            float64
 68   Y1980F           object
 69   Y1980N           float64
 70   Y1981            float64
 71   Y1981F           object
 72   Y1981N           float64
 73   Y1982            float64
 74   Y1982F           object
 75   Y1982N           float64
 76   Y1983            float64
 77   Y1983F           object
 78   Y1983N           float64
 79   Y1984            float64
 80   Y1984F           object
 81   Y1984N           float64
 82   Y1985            float64
 83   Y1985F           object
 84   Y1985N           float64
 85   Y1986            float64
 86   Y1986F           object
 87   Y1986N           float64
 88   Y1987            float64
 89   Y1987F           object
 90   Y1987N           float64
 91   Y1988            float64
 92   Y1988F           object
 93   Y1988N           float64
 94   Y1989            float64
 95   Y1989F           object
 96   Y1989N           float64
 97   Y1990            float64
 98   Y1990F           object
 99   Y1990N           object
 100  Y1991            float64
 101  Y1991F           object
 102  Y1991N           object
 103  Y1992            float64
 104  Y1992F           object
 105  Y1992N           object
 106  Y1993            float64
 107  Y1993F           object
 108  Y1993N           object
 109  Y1994            float64
 110  Y1994F           object
 111  Y1994N           object
 112  Y1995            float64
 113  Y1995F           object
 114  Y1995N           object
 115  Y1996            float64
 116  Y1996F           object
 117  Y1996N           object
 118  Y1997            float64
 119  Y1997F           object
 120  Y1997N           object
 121  Y1998            float64
 122  Y1998F           object
 123  Y1998N           object
 124  Y1999            float64
 125  Y1999F           object
 126  Y1999N           object
 127  Y2000            float64
 128  Y2000F           object
 129  Y2000N           object
 130  Y2001            float64
 131  Y2001F           object
 132  Y2001N           object
 133  Y2002            float64
 134  Y2002F           object
 135  Y2002N           object
 136  Y2003            float64
 137  Y2003F           object
 138  Y2003N           object
 139  Y2004            float64
 140  Y2004F           object
 141  Y2004N           object
 142  Y2005            float64
 143  Y2005F           object
 144  Y2005N           object
 145  Y2006            float64
 146  Y2006F           object
 147  Y2006N           object
 148  Y2007            float64
 149  Y2007F           object
 150  Y2007N           object
 151  Y2008            float64
 152  Y2008F           object
 153  Y2008N           object
 154  Y2009            float64
 155  Y2009F           object
 156  Y2009N           object
 157  Y2010            float64
 158  Y2010F           object
 159  Y2010N           object
 160  Y2011            float64
 161  Y2011F           object
 162  Y2011N           object
 163  Y2012            float64
 164  Y2012F           object
 165  Y2012N           object
 166  Y2013            float64
 167  Y2013F           object
 168  Y2013N           object
 169  Y2014            float64
 170  Y2014F           object
 171  Y2014N           object
 172  Y2015            float64
 173  Y2015F           object
 174  Y2015N           object
 175  Y2016            float64
 176  Y2016F           object
 177  Y2016N           object
 178  Y2017            float64
 179  Y2017F           object
 180  Y2017N           object
 181  Y2018            float64
 182  Y2018F           object
 183  Y2018N           object
 184  Y2019            float64
 185  Y2019F           object
 186  Y2019N           object
 187  Y2020            float64
 188  Y2020F           object
 189  Y2020N           object
 190  Y2021            float64
 191  Y2021F           object
 192  Y2021N           float64
 193  Y2030            float64
 194  Y2030F           object
 195  Y2030N           float64
 196  Y2050            float64
 197  Y2050F           object
 198  Y2050N           float64
dtypes: float64(95), int64(4), object(100)
memory usage: 89.2+ MB